### ISSUE TITLE
Codelite runs for a second then silently exits

### ISSUE THREAD

**Issue by phaikawl** [eranif/codelite#937] opened 2015-09-29 01:49 UTC
I compiled latest git codelite on Arch Linux. When I run it in the terminal, codelite shows the splash image, in the terminal then the following is printed
    
    07:51:33: Warning: Mismatch between the program and library build versions detected.
    The library used 3.0 (wchar_t,compiler with C++ ABI 1008,wx containers,compatible with 2.8),
    and your program used 3.0 (wchar_t,compiler with C++ ABI 1009,wx containers,compatible with 2.8).

It's just a warning, but after that codelite just exits, no window is shown, without any further error messages.
The same compiled codelite was working on my machine just last night, I'm not really sure what happened. I tried reinstalling wxgtk, clean and rebuilding codelite and all but it nothing changes.
I then compiled wxgtk myself with --disable-asserts, it would not print that warning anymore, but the situation isn't improved at all, it runs for a second and exits, now it prints literally nothing.

**Comment by eranif** [comment] 2015-09-29 05:42
As it works for me on Debian 8 / Ubuntu 15.04 I can't really tell why it fails for you.
You can:
* `git pull --rebase` and then rebuild CodeLite (re-run `cmake` and then install it) and try again
* Check for anything useful in `~/.codelite/codelite-stdout-stderr.log` file
* Try running without any plugins and see if it loads: `codelite --no-plugins`
* Run `CodeLite` under `gdb` and see why it fails

**Comment by phaikawl** [comment] 2015-09-29 07:17
Thanks so much for the right pointers!
I tried `--no-plugins` and it runs, that's a good sign.
So the command line messages are all redirected to `~/.codelite/codelite-stdout-stderr.log`, isn't it?
The error message I find in there when running codelite (without `--no-plugins`) is:
    
    : CommandLine Error: Option 'aarch64-reserve-x18' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options
And no such message is produced when I run codelite with `--no-plugins`. So I believe that's indead the problem.

**Comment by eranif** [comment] 2015-09-29 08:43
This seems like a bug in LLDB (liblldb-3.7) (search the above error in Google and you will see many similar reports)
To fix this, you can simply delete LLDB plugin from your file system, by default it is placed here `/usr/lib/x86_64-linux-gnu/codelite/LLDBDebugger.so`

I will fix CodeLite build system to ignore lldb-3.7

**Comment by uffejakobsen** [comment] 2015-09-29 09:17
I have exact the same problem on ArchLinux after update to clang/llvm-3.7.

: CommandLine Error: Option 'aarch64-reserve-x18' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options


I can start CodeLite with no-plugins (-n) option - but I cannot seem to find what plugin that causes the problem - I have tried to enable the plugins one-by-one. As soon as I just enable one random plugin the above problem occours - my guess is that the -n option does more than just disable all the plugins ?

**Comment by eranif** [comment] 2015-09-29 10:28
Should be fixed. Please rebuild CodeLite (you need to re-run `cmake`)

**Closed by eranif** 2015-09-29 10:28 UTC

**Comment by phaikawl** [comment] 2015-09-29 14:31
I pulled, then rebuilt codelite. I even cleaned and built it all again. But after all that, same problem, same error message :(.

**Comment by eranif** [comment] 2015-09-29 16:15
The reason for this might be that you have LLDBDebugger.so already installed from previous builds.
`sudo make install` does not uninstall first.
Try deleting the folder `/usr/lib/x86_64-linux-gnu/codelite`  and then re-install CodeLite

After the install, check that `/usr/lib/x86_64-linux-gnu/codelite/LLDBDebugger.so` does not exist

**Comment by eranif** [comment] 2015-09-30 08:02
A confirmed working solution (tested on ArchLinux)

You will need to remove the file `CMakeCache.txt`
Build CodeLite with the cmake flag: `-DENABLE_LLDB=0`
