### ISSUE TITLE
FSW project with ctagsd does not index all files  

### ISSUE THREAD

**Issue by uffejakobsen** [eranif/codelite#2956] opened 2022-02-13 00:01 UTC
FSW project with ctagsd does not index all files  

Starting from scratch:

I cloned a randomly chosen project from github (from a terminal)
Then I created a FSW workspace for that project.

After that I use "Open Resources..." to find symbols/functions that I for sure know are in the source - but they do not show up in the dialog.

No matter what I do - the files in the project are not indexed unless they are individually opened in Codelite.

CL-15.0.10

**Comment by uffejakobsen** [comment] 2022-02-13 00:08
Additional info:

Looking in the `.ctagsd/tags.db` confirms my report - only the files that have been opened in the editor are indexed.

**Comment by eranif** [comment] 2022-02-13 08:26
I don't think that the problem is with `ctagsd`. I did the same and opened a c++ workspace after deleting its `.ctagsd/` folder
the DB seems to be populated properly.
However, doing `Ctrl-Shift-R` did not show the results in the `Open resource` dialog. 

I suspect that the problem is within the UI or something with the generated output.
If you switch enhance `ctagsd` logging level (plugins -> language server -> ctagsd) under the command, set the `--log-level` to `TRACE` and then check the output under:

`tail -f ~/.ctagsd/ctagsd.log` - can you confirm that `ctagsd` indeed return the methods you are expecting?

**Comment by eranif** [comment] 2022-02-13 09:29
I think I found the problem.
The database is updated, the problem is due to the fact that the initial parsing is done in a background thread
Moving `ctagsd` initialization to the main threads solves the issue.
can you try it with the latest master?

as a side effect `ctagsd` will be "ready" to work after ~5 seconds or less. But it will report correct and full answers once its completed its initialization.

I also updated the `Language Server` with 2 messages indicating that the initialization is in progress

**Comment by uffejakobsen** [comment] 2022-02-13 18:29
Hi,
I'm sorry the latest corrections in master does not make any difference.

Try to clone this project (as an example):
https://github.com/gideont/hello_world.git

Then create a FSW project for it within Codelite
Do not open any of its source files yet.

It is my understanding that if the whole project was indexed by the above steps.
But it is not.

dumping the `FILES` table in the `..ctagsd/tags.db` using this command returns 0 rows:

sqlite3 .ctagsd/tags.db 'select * from files;'

Only when I start opening source files the FILES table begin to contain rows like this:

```
1|/tmp/test.dir/gideont-hello_world.git/07_thread/example.cpp|1644776371
```

But only the files that have been opened in the CL editor..

Is it wrong to assume that all the source files should have been indexed from the beginning ?

**Comment by eranif** [comment] 2022-02-13 18:57
I did exactly as you suggested and for me the table `FILES` is populated with all the source files.

```
eran@DESKTOP-F7URLL7 MSYS /c/src/hello_world/.ctagsd
$ /usr/bin/sqlite3 tags.db
SQLite version 3.35.5 2021-04-19 18:32:05
Enter ".help" for usage hints.
sqlite> select * from FILES;
1|C:\src\hello_world\04_c++11_cmake\src\hello.cpp|1644777943
2|C:\src\hello_world\04_c++11_cmake\src\foo.cpp|1644777943
3|C:\src\hello_world\04_c++11_cmake\include\foo.hpp|1644777943
4|C:\src\hello_world\07_thread\example.cpp|1644777943
5|C:\src\hello_world\05_cmake_lib\hello.cpp|1644777943
6|C:\src\hello_world\05_cmake_lib\mylib.cpp|1644777943
7|C:\src\hello_world\01_hello_world\hello.c|1644777943
8|C:\src\hello_world\03_cmake\include\foo.h|1644777943
9|C:\src\hello_world\02_shared_lib\include\foo.h|1644777943
10|C:\src\hello_world\06_namespace_class\example.cpp|1644777943
11|C:\src\hello_world\05_cmake_lib\mylib.hpp|1644777943
12|C:\src\hello_world\08_interface\example.cpp|1644777943
13|C:\src\hello_world\03_cmake\src\hello.c|1644777943
14|C:\src\hello_world\02_shared_lib\src\foo.c|1644777943
15|C:\src\hello_world\02_shared_lib\src\hello.c|1644777943
16|C:\src\hello_world\03_cmake\src\foo.c|1644777943
```

**Comment by eranif** [comment] 2022-02-13 18:57
as you can see from the timestamp -> (the last column) they were all parsed at the same time

**Comment by eranif** [comment] 2022-02-13 19:11
I will keep looking into this

**Comment by eranif** [comment] 2022-02-13 20:47
I found an interesting bug in the code...
when an LSP response was received by CodeLite it did a check that an active editor is opened (this was mainly for the "completion" requests). However, most of the responses do not require an active editor to be opened, e.g. the `workspace/symbol` . Since you did not open any file in CodeLite, the response was dropped.

With the latest master, if you open **any** file and then do `Ctrl-Shift-R` of a symbol that does not belong to the current file, does it work for you?

NOTE: this still does not explain why your `FILES` table is empty...

**Comment by uffejakobsen** [comment] 2022-02-14 01:31
Ok - found the problem - made a pull request

Any path containing a matching ignore spec above the root path would make an erroneous match as function filter_non_important_files() uses Contains() on the full file path
Make the ignore specs precise - add path separators on both sides of .git and .svn etc

I usually name my project root dirs with a extension that indicate what VCS system is used - eg `some-project-root-dir-name.git`

The above naming would cause a problem as ctagsd does not know where the project root path is - and uses absolute paths to all the files.

The original ignore specs `.git/` and `.svn/` would generate an incorrect ignore spec above the project root path match - and would prevent ctagsd from seeing any source files at all...

**Comment by eranif** [comment] 2022-02-14 12:41
with the merge of the fix, I am going to close this issue

**Closed by eranif** 2022-02-14 12:41 UTC
