### ISSUE TITLE
Goto definition doesn't work with methods inherited from PHP Traits

### ISSUE THREAD

**Issue by jclaveau** [eranif/codelite#944] opened 2015-10-06 10:12 UTC
Example
```php
<?php
abstract class Generic_Tests_DatabaseTestCase extends PHPUnit_Extensions_Database_TestCase
{
	use FixtureGeneratorTestCaseTrait;
	use PersistenceTestCaseTrait;

	public static function setUpBeforeClass() {
		self::_prepareFixtures();
	}
}
```
With "_prepareFixtures" defined in FixtureGeneratorTestCaseTrait.php.

If you right click on "_prepareFixtures" and then on "Goto definition", nothing happens.

**Comment by eranif** [comment] 2015-10-06 10:15
Thanks for the detailed reproduction script (this way I can add it to unit tests :))

**Comment by jclaveau** [comment] 2015-10-06 10:19
Glad to help! An other important case for this issue is the PHP conflicts resolution between multiple traits. Good examples are provided here : 
http://php.net/manual/fr/language.oop5.traits.php

```php
<?php
trait A {
    public function smallTalk() {
        echo 'a';
    }
    public function bigTalk() {
        echo 'A';
    }
}

trait B {
    public function smallTalk() {
        echo 'b';
    }
    public function bigTalk() {
        echo 'B';
    }
}

class Talker {
    use A, B {
        B::smallTalk insteadof A;
        A::bigTalk insteadof B;
    }
}

class Aliased_Talker {
    use A, B {
        B::smallTalk insteadof A;
        A::bigTalk insteadof B;
        B::bigTalk as talk;
    }
}
?>
```

**Comment by eranif** [comment] 2015-10-06 10:25
Thanks again!

**Comment by eranif** [comment] 2015-10-07 03:17
I think that the first case failed because the method `_prepareFixtures` is not `static`
I assumed that only static functions are to be shown with `self::` 
I was wrong here, `self::` should present static members _and_ all functions. I fixed this and added a test case to the PHP code completion UT

**Comment by eranif** [comment] 2015-10-07 04:20
(GitHub closed the bug automatically..)

**Comment by jclaveau** [comment] 2015-10-07 05:06
I don't know if you noticed it but clicking on "use FixtureGeneratorTestCaseTrait;" doesn't work neither. Considering my little piece of code, _prepareFixtures is really static :) .

**Comment by eranif** [comment] 2015-10-07 06:35
> I don't know if you noticed it but clicking on "Goto definition" on "use FixtureGeneratorTestCaseTrait;" 
> doesn't work neither. Considering my little piece of code, _prepareFixtures is really static :) .

There was some bad handling with `self::` in the parser, should be fixed now. I also improved the `use A, B {..}` parsing
I am now working on aliasing of functions. it seems that I need to introduce some kind of new entity "Function Alias" which points to the actual function and is kept in the database (this is because at parsing of a single translation unit, the actual function is not known to the parser, but only later to the lookup table)

**Closed** 2015-10-07 15:01 UTC
