### ISSUE TITLE
parser/autocomplete has problems with c++ files/constructions

### ISSUE THREAD

**Issue by tommeschberlin** [eranif/codelite#1601] opened 2017-03-15 12:32 UTC
I get an autocompletion for "shared_future" should be declared in /usr/include/c++/4.9/future
but not for "recursive_mutex" (typeing rec) should be declared in the file /usr/include/c++/4.9/mutex

Looks like the parser has problems with some files/construcitons, because I observed similar problems for "Goto Declaration/Implementation" and "Search->Find References ..." too.

**Comment by eranif** [comment] 2017-03-15 13:05
This can't be fixed in a reasonable manner.
The problem is that the definition is indeed found in that file

**Comment by tommeschberlin** [comment] 2017-03-15 14:25
eranif encouraged me to dig a little bit deeper, I found some of the missed tags in the tags db but does'nt see them as suggestion, so I deleted all tags / refactoring db. After codelite has rebuild them I surprisingly looks like as it now works.

**Closed** 2017-03-15 14:26 UTC
