### ISSUE TITLE
Could not launch terminal for debugger

### ISSUE THREAD

**Issue by erniepb** [eranif/codelite#1206] opened 2016-03-15 14:45 UTC
Hello, I have the following issue, using the latest pull from the git repository, I always get the same error "Could not launch terminal for debugger", whenever I try to debug my code. Global preferences say to use xterm, i.e., /usr/bin/xterm '$(TITLE)' '$(CMD)'. codelite_xterm does not work either. Using the same workspace with codelite 9.1, i.e., 5e6fe0d from the repository works just fine with xterm.

Thanks for any help.

**Comment by dghart** [comment] 2016-03-15 21:22
Hi,
A week ago I made a change that allows terminals other than xterm also to be used. I obviously checked that xterm still worked though.

Maybe I didn't test your particular distro ( I presume you are using Linux). Which distro/version is it?
And if you do, in a terminal:
x-terminal-emulator
does it successfully run xterm?

Thanks for your help.
Regards,
David

**Comment by erniepb** [comment] 2016-03-16 08:41
Hi, thanks for the reply.
I am on Fedora 23 (and also Fedora 22) 64-bit.
Trying to execute 'x-terminal-emulator' in a terminal yields an error saying it is not available. Indeed it does not seem to be available in any package for Fedora.
Thank you!!

**Comment by dghart** [comment] 2016-03-16 22:26
Ah, I'd obviously not tested well enough there. Sorry.

This should be fixed by commit 32acc63. Unfortunately it means fedora-users are stuck with xterm again; I hope you like it more than I do :(

**Closed by dghart** 2016-03-16 22:26 UTC

**Comment by jiapei100** [comment] 2017-01-30 23:53
I've been using Ubuntu 16.04.1, this issue seems to still pop out from time to time for me...
In the same workspace, some projects can be successfully debugged, but other won't. There is always a dialog saying "Could not launch terminal for debugger" ...

**Comment by Efluminor** [comment] 2017-03-03 23:52
Hello,

I have migrated from codelite 9.1 to codelite 10.0.0 and I was surprised by the error "Could not launch terminal for debugger".

Investigating a little bit, the file codelite_xterm resolve terminal in ubuntu based distros to x-terminal-emulator, in my case this terminal is pantheon-terminal.

My workaround to bypass the problem is force in the file codelite_xterm to use like terminal = "xterm -sb -sl 1000" and now works.

I'm using elementary OS.

Kind regards.

**Comment by dghart** [comment] 2017-03-04 10:26
Hi,
> in my case this terminal is pantheon-terminal

I didn't test that one; indeed this is the first time I've heard of it.

>My workaround to bypass the problem is force in the file codelite_xterm to use like terminal = "xterm -sb -sl 1000"

That's the right thing to do, if you don't want to set x-terminal-emulator to a different terminal that _does_ work in CodeLite.

Regards,
David
