### ISSUE TITLE
compile_commands.json discovery

### ISSUE THREAD

**Issue by jdumas** [eranif/codelite#938] opened 2015-09-30 10:40 UTC
This feature doesn't have much documentation, so I've been reading the source code of `compilation_database.cpp` to understand how the `compile_commands.json` file generated by CMake is discovered.

Now, it seems that the lookup is a bit heuristic, traversing directories recursively and all. But in the case of a CMake project, the `compile_commands.json` is generated in the directory where the build happens, so wouldn't it make more sense to use the 'Build directory' option of the CMake tab in Codelite to look for this `compile_commands.json` file ? That way it would work with arbitrary build directories (not only those which are at depth < 2 from the toplevel directory).

**Comment by eranif** [comment] 2015-09-30 10:56
> so wouldn't it make more sense to use the 'Build directory' option of the CMake tab in Codelite to look 
> for this compile_commands.json file

In general, I would agree. However, this information is part of a plugin. CodeLite itself is not aware of the plugin existence so it can not access this info

I agree that the above will not work for building completely out of the source tree, however, I do plan on writing a complete new support for CMake which works as intended and not in the hackish way of the current plugin

**Comment by jdumas** [comment] 2015-09-30 11:06
I see. I look forward to see the new support for CMake then!

**Comment by eranif** [comment] 2015-09-30 17:42
I am closing this, as there is nothing really to fix here

**Closed by eranif** 2015-09-30 17:42 UTC
