### ISSUE TITLE
New Project dialog resizing problem

### ISSUE THREAD

**Issue by neolib** [eranif/codelite#1344] opened 2016-07-18 14:39 UTC
The New Project dialog has a resizing problem. See attachment screenshot.
![screen shot 2016-07-18 at 8 46 16 pm](https://cloud.githubusercontent.com/assets/10727052/16918568/80fec5f2-4d38-11e6-8118-092dcbd2daa2.png)

**Comment by eranif** [comment] 2016-07-18 14:42
As mentioned on the forum:
Please state your CodeLite version, OS used etc... don't spare on the details

**Comment by neolib** [comment] 2016-07-19 07:02
Tested using CodeLite 9.20. The problem is not pertinent to a specific OS.

**Comment by eranif** [comment] 2016-07-19 07:50
If you attempt to resize a wxWizard based dialog - this is what you get...
Its a bug in wxWidgets http://trac.wxwidgets.org/ticket/17528 and a duplicate of https://github.com/eranif/codelite/issues/1274

**Closed by eranif** 2016-07-19 07:50 UTC
