### ISSUE TITLE
Codelite complete freeze

### ISSUE THREAD

**Issue by cisou98** [eranif/codelite#1341] opened 2016-07-16 15:20 UTC
Hi, when I try to access to Workspace's setting panel in codelite the application freeze. I tried uninstalling + reinstalling (9.2 and 9.1) but nothings work anymore... 

I am running on windows 8.1.

**Comment by eranif** [comment] 2016-07-16 16:26
I can think of a reason why this happens.

I can advise you to try this:

1. Close CodeLite
2. Rename the folder `%appdata%\CodeLite` to something else
3. Start CodeLite

This still happens?

If it does, try loading CodeLite without Plugins from the command line like this:
`"C:\Program Files\CodeLite\codelite.exe" --no-plugins` (assuming you installed CodeLite at C:\Program Files)

**Comment by cisou98** [comment] 2016-07-16 16:58
Indeed, the git plugin was freezing the whole program. I disabled it and it now works as usual. My favorite IDE btw :+1:  :)

**Comment by eranif** [comment] 2016-07-16 17:00
Thanks!
I am closing this, as it seems to me an environmental issue (i.e. I am running CodeLite on 4 different Windows boxes without this issue, so I doubt I will be able to debug this)

If, for some reason, you found the root cause - feel free to reopen this with the additional info

**Closed by eranif** 2016-07-16 17:00 UTC
