### ISSUE TITLE
Codelite crashes when trying to start debugger

### ISSUE THREAD

**Issue by radekg1000** [eranif/codelite#1231] opened 2016-04-08 15:39 UTC
Codlite crashes when trying to start debugger.
The problems start even before starting the debugging and after having downloaded the workspace file. The workspace file has the Project Active field set to "Yes" but the project itself is not active. On an attempt to start the debugger in this state codelite crashes.
When setting the Project to Active (i.e. left click on the project and "Make Active (double click)" this flag seams to flip and is saved as "No". On an attempt to start the debugger codelite repetitively says "Attempting to debug workspace with no active project" Ignoring." 
Interestingly the crash happens for the "arc" workspace, but does not for "ms2x12" (please see the attached files).
I tried to identify the problem by running codelite in debug mode but it seams too big for me to comprehend in short amount of time.
[ms2x12.zip](https://github.com/eranif/codelite/files/210405/ms2x12.zip)
[arc.zip](https://github.com/eranif/codelite/files/210406/arc.zip)
[codelite_crash.txt](https://github.com/eranif/codelite/files/210398/codelite_crash.txt)

My OS: Linux Ubuntu 14.04 64-bit
codelite version: 9.1.0 or upstream version from github compiled in Debug mode

Radek

**Comment by eranif** [comment] 2016-04-08 15:41
Not a bug. You have a corrupted workspace file. Two projects are marked as "active"

**Closed by eranif** 2016-04-08 15:41 UTC

**Comment by radekg1000** [comment] 2016-04-08 15:59
Sorry, the other line was added by codelite somehow. After having removed it codelite still crashes or opens as not active in spite of Active flag set. Is there something wrong about the Project file?
[arc.zip](https://github.com/eranif/codelite/files/210441/arc.zip)

**Comment by eranif** [comment] 2016-04-09 09:39
Did you hand edit the project/workspace file? I can't see an option that the project name and the actual file have different names (one with space and the other without it)

You are not suppose to edit these files by hand
