### ISSUE TITLE
Code completition (with ctags) doesn't find getLocStart of Decl based classes/object in clang + llvm.

### ISSUE THREAD

**Issue by 05storm26** [eranif/codelite#730] opened 2015-04-18 08:27 UTC
Get llvm 3.6, get the corresponding clang and put it into the llvm/tools directory, then get clang-tools-extra and put that into llvm/tools/clang/tools/extra/. 

Go to a clang-extra plugin for example clang-modernize, llvm/tools/clang/tools/extra/clang-modernize/ReplaceAutoPtr/ReplaceAutoPtrActionsActions.cpp go  to AutoPtrReplacer::run (line 45) go to the 53-line into the else part where it gets an const UsingDecl * as 'const UsingDecl *D = Result.Nodes.getNodeAs<UsingDecl>(AutoPtrTokenId);'. 

Now below that you write in 'D->get' <ctrl + space > and even though you do get a lot of symbols in the appearing code completition list you don't get everything, you don't get getLocStart(), getLocEnd(), and getSourceLocation().

UsingDecl is declared in DeclCXX.h and based on NamedDecl which is based on Decl, which does defines getLocStart(). Same is true for other derived classes like FunctionDecl.

If you need more information please tell me. I have codelite based on afa4bb3a6e331b9f76fb42fe7ffba70b4a464fe9.

**Comment by eranif** [comment] 2015-04-18 08:40
What happens if you enable clang code completion? Does it work?

**Comment by 05storm26** [comment] 2015-04-18 10:14
I tried it. With it sometimes it works sometimes it doesn't. With the shipped plugins it works, but with, a custom made it doesn't, even thought it compiles, and it were compilied together. Do I need to recompile (I mean clean and recompile completely) the whole thing every time I add a file? That would take just too much time. Compiling the whole stuff described above takes several hours (1-2,5).

In the clang-modernze if I write 'D->getL' I don't see getLocStart in the list but if I write getLoc which is doesn't matched by anything that you could see in the list previously than it appears in the list. This is not good. Also the fact that you have to recompile it completle to get clang code completition is not easy if you have a big project. 

Couldn't code completition with ctags just work?

BTW: Decl has an interesting macro maybe this is the reason why ctags fails?

'#define DECL(DERIVED, BASE) DERIVED,'

**Comment by eranif** [comment] 2015-04-18 10:17
No need to recompile everything, you just need to export the build commands (assuming you are using `CMake`)
See my blog post: http://codeliteide.blogspot.co.il/2014/02/codelite-ide-60-cmake-and-clang-code.html

**Comment by 05storm26** [comment] 2015-04-18 10:55
I do use cmake. I set it up in the project settings page cmake page. I already had  a compile_commands.json file. Still doesn't work with my plugin.

**Comment by luckyrandom** [comment] 2015-04-19 18:06
@eranif I'd like to report the support of compile_command.json doesn't work. I'm using CodeLite 7.0 on Mac. With following two files in directory, run

```
  cmake . -DCMAKE_EXPORT_COMPILE_COMMANDS=1 -G "CodeLite - Ninja"
```

I confirm the compile_commands.json is correct, including `/opt/local/include`, where boost is stored. The autocomplete for `boost::shared_ptr` and `pA.get` doesn't work. With clang option on, it complains
```
clang: use of undeclared identifier 'boost'
'A' does not refer to a value
declared here
use of undeclared identifier 'pA'
```

Turn log level of CodeLite to debug, I don't see any log related to `compile_command.json`, while I expect them from method `CompilationDatabase::GetCompileCommandsFiles`. Furthermore, the log shows the command line argument doesn't include the boost directory.
```
Command Line Argument: -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include
[ 12:41:54:591 DBG ] Command Line Argument: -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1
[ 12:41:54:591 DBG ] Command Line Argument: -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/6.0/include
[ 12:41:54:592 DBG ] Command Line Argument: -I/Library/Frameworks
[ 12:41:54:592 DBG ] Command Line Argument: -I/System/Library/Frameworks
[ 12:41:54:593 DBG ] Command Line Argument: -I/usr/include
[ 12:41:54:593 DBG ] Command Line Argument: -I/usr/local/include
[ 12:41:54:594 DBG ] Command Line Argument:
[ 12:41:54:594 DBG ] Command Line Argument: -w
[ 12:41:54:595 DBG ] Command Line Argument: -ferror-limit=1000
[ 12:41:54:595 DBG ] Command Line Argument: -nobuiltininc
```

Content of CMakeLists.txt
```cmake
# CMakeLists files in this project can
# refer to the root source directory of the project as ${HELLO_SOURCE_DIR} and
# to the root binary directory of the project as ${HELLO_BINARY_DIR}.
cmake_minimum_required (VERSION 2.8.11)
project (HELLO)

find_package(Boost 1.36.0)
if(Boost_FOUND)
  include_directories(${Boost_INCLUDE_DIRS})
endif()

add_executable (Hello hello.cxx)
```

Content of hello.cxx
```cxx
#include <boost/smart_ptr/shared_ptr.hpp>
#include <iostream>
#include <memory>

class A{};
int main()
{
	boost::shared_ptr<A> pA(new A);
	std::cout << pA.get() << std::endl;
	boost::shared_ptr<A> pB(pA);
	std::cout << pA.get() << std::endl;
	std::cout << pB.get() << std::endl;
	return 0;
}
```

**Comment by eranif** [comment] 2015-04-19 18:16
@luckyrandom This bug was fixed 9 days after CodeLite 7.0 was released.
See this commit https://github.com/eranif/codelite/commits/bdb7e8110f473459b15208fa1c4e977423b2499c

I really hope that CodeLite 7.1 will be available in the coming weeks. However, if you are using OSX, they I suggest that you download the latest weekly build for OSX which has this fix included (you can get it from the usual download page on http://codelite.org )

**Comment by luckyrandom** [comment] 2015-04-19 20:28
@eranif It seems not fixed in the weekly build version, with the same error. Could you please double check? At one time, it shows a warning that I should set environment variable CXX and CC for custom build. I follow the instruction and set that in Project Setting -> Environment, but seems has no effect. I wonder why shall we set that, since CodeLite knows it is a custom build. Another related question is that I can't reproduce the warning, and I only see it once.

By the way, the downloaded file is end in `targz`, which should be `tar.gz`.

**Comment by eranif** [comment] 2015-12-24 04:55
> I wonder why shall we set that, since CodeLite knows it is a custom build

Because its a custom build, and CodeLite does not really know which compiler you plan on using (clang, xlc, gcc etc)

> By the way, the downloaded file is end in targz, which should be tar.gz

This is already fixed.

Extending ctags code completion is beyond my scope atm and all attention is addressed to clang
so this is unlikely to be fixed in the foreseeable future (pull requests are welcome)

**Closed by eranif** 2015-12-24 04:55 UTC
