### ISSUE TITLE
Parameter suggestions not working for constructors.

### ISSUE THREAD

**Issue by Crafter213** [eranif/codelite#808] opened 2015-06-02 14:21 UTC
Using: CodeLite 8.0 on Windows 7

When using e.g. SFML's Vector2f, CodeLite seems not to be able to show, wich parameters are required.
Constructor with expected suggestions: Vector2f(float x, float y).

**Comment by eranif** [comment] 2015-06-02 14:34
Again, please provide a zipped project that shows the problem.
minimal code snippets does not help here

**Comment by Crafter213** [comment] 2015-06-02 18:33
I am sorry, this can be deleted. See #809

**Comment by eranif** [comment] 2015-06-02 18:39
Duplicate of #809

**Closed by eranif** 2015-06-02 18:39 UTC
