### ISSUE TITLE
Codelite adding compiler options to the FileName

### ISSUE THREAD

**Issue by larivierec** [eranif/codelite#992] opened 2015-10-27 15:42 UTC
Good evening,

Im simply letting you guys know that Codelite seems to be adding the compiler options directly into the file name when you build.

![image](https://cloud.githubusercontent.com/assets/3633214/10763296/c93a0580-7c9f-11e5-87ee-34571a9af1ee.png)

**Comment by eranif** [comment] 2015-10-28 08:14
From the output of the build tab, it looks like a bug in the compiler... you can clearly see that there is a space between the file name and the `-g` option.
Also, the file name is enclosed within double quotes
What happens if you run this command from the command line?

**Comment by mtangoo** [comment] 2015-10-28 09:20
Whic version of CL and MINGW are you using.
with CL 9.0.1 and GCC 4.8.1 it works fine

```
C:\WINDOWS\system32\cmd.exe /C C:/MinGW/bin/mingw32-make.exe -j4 SHELL=cmd.exe -e -f  Makefile
"----------Building project:[ Notebook - Debug ]----------"
mingw32-make.exe[1]: Entering directory 'C:/Projects/Hosanna/Notebook/Notebook'
C:/MinGW/bin/windres.exe -i "C:/Projects/Hosanna/Notebook/Notebook/win_resources.rc" --use-temp-file --define __WXMSW__ --define __WXDEBUG__ --define _UNICODE --include-dir C:/wxWidgets-3.0.2/lib/gcc_dll/mswud --include-dir C:/wxWidgets-3.0.2/include --define WXUSINGDLL    -o ./Debug/win_resources.rc.o
C:/MinGW/bin/g++.exe  -c  "C:/Projects/Hosanna/Notebook/Notebook/main.cpp" -g -O0 -Wall -mthreads -DHAVE_W32API_H -D__WXMSW__ -D__WXDEBUG__ -D_UNICODE -IC:/wxWidgets-3.0.2/lib/gcc_dll/mswud -IC:/wxWidgets-3.0.2/include -DWXUSINGDLL -Wno-ctor-dtor-privacy -pipe -fmessage-length=0     -o ./Debug/main.cpp.o -I. -I.
C:/MinGW/bin/g++.exe  -c  "C:/Projects/Hosanna/Notebook/Notebook/MainFrame.cpp" -g -O0 -Wall -mthreads -DHAVE_W32API_H -D__WXMSW__ -D__WXDEBUG__ -D_UNICODE -IC:/wxWidgets-3.0.2/lib/gcc_dll/mswud -IC:/wxWidgets-3.0.2/include -DWXUSINGDLL -Wno-ctor-dtor-privacy -pipe -fmessage-length=0     -o ./Debug/MainFrame.cpp.o -I. -I.
C:/MinGW/bin/windres.exe: warning: 24: 1: 1033: duplicate value
C:/MinGW/bin/g++.exe  -c  "C:/Projects/Hosanna/Notebook/Notebook/wxcrafter.cpp" -g -O0 -Wall -mthreads -DHAVE_W32API_H -D__WXMSW__ -D__WXDEBUG__ -D_UNICODE -IC:/wxWidgets-3.0.2/lib/gcc_dll/mswud -IC:/wxWidgets-3.0.2/include -DWXUSINGDLL -Wno-ctor-dtor-privacy -pipe -fmessage-length=0     -o ./Debug/wxcrafter.cpp.o -I. -I.
C:/MinGW/bin/g++.exe  -c  "C:/Projects/Hosanna/Notebook/Notebook/wxcrafter_bitmaps.cpp" -g -O0 -Wall -mthreads -DHAVE_W32API_H -D__WXMSW__ -D__WXDEBUG__ -D_UNICODE -IC:/wxWidgets-3.0.2/lib/gcc_dll/mswud -IC:/wxWidgets-3.0.2/include -DWXUSINGDLL -Wno-ctor-dtor-privacy -pipe -fmessage-length=0     -o ./Debug/wxcrafter_bitmaps.cpp.o -I. -I.
C:/MinGW/bin/g++.exe  -c  "C:/Projects/Hosanna/Notebook/Notebook/Notebook.cpp" -g -O0 -Wall -mthreads -DHAVE_W32API_H -D__WXMSW__ -D__WXDEBUG__ -D_UNICODE -IC:/wxWidgets-3.0.2/lib/gcc_dll/mswud -IC:/wxWidgets-3.0.2/include -DWXUSINGDLL -Wno-ctor-dtor-privacy -pipe -fmessage-length=0     -o ./Debug/Notebook.cpp.o -I. -I.
C:/MinGW/bin/g++.exe  -c  "C:/Projects/Hosanna/Notebook/Notebook/notebook_bitmaps.cpp" -g -O0 -Wall -mthreads -DHAVE_W32API_H -D__WXMSW__ -D__WXDEBUG__ -D_UNICODE -IC:/wxWidgets-3.0.2/lib/gcc_dll/mswud -IC:/wxWidgets-3.0.2/include -DWXUSINGDLL -Wno-ctor-dtor-privacy -pipe -fmessage-length=0     -o ./Debug/notebook_bitmaps.cpp.o -I. -I.
C:/MinGW/bin/g++.exe  -c  "C:/Projects/Hosanna/Notebook/Notebook/windowstack.cpp" -g -O0 -Wall -mthreads -DHAVE_W32API_H -D__WXMSW__ -D__WXDEBUG__ -D_UNICODE -IC:/wxWidgets-3.0.2/lib/gcc_dll/mswud -IC:/wxWidgets-3.0.2/include -DWXUSINGDLL -Wno-ctor-dtor-privacy -pipe -fmessage-length=0     -o ./Debug/windowstack.cpp.o -I. -I.  
```

**Comment by larivierec** [comment] 2015-10-28 18:28
@eranif yes I did realise this, however, before installing to Windows 10 this was never a problem my project was working fine with this compiler.

@mtangoo I'm using: ARM GCC 4.8.2, maybe I should update to a newer version?

**Comment by larivierec** [comment] 2015-10-29 04:03
I can confirm that I have tried this with ARM GCC GNUEABIHF 5.1 on Windows 10 and I get the same problem. My compiler options are always shown in the file name for compilation.

**Comment by eranif** [comment] 2015-10-31 10:05
@larivierec I am not sure how to continue with this, as its clearly a bug in either Windows/ARM GCC
There is a space between the file name (which itself is enclosed within double quotes) and the `-g` option.

Can you try and compile a single file from the command line? and see if the results are the same?

**Comment by eranif** [comment] 2015-10-31 10:17
@larivierec try changing the `make` utility. I see that in your build screenshot, you are using `D:\Software\GCC\bin\mingw32-make.exe` see if you can replace it with something else, maybe you got new one under `D:\Software\LinaroGCC\bin` folder

**Comment by larivierec** [comment] 2015-10-31 14:00
I'll try changing this, if it doesn't work I'll try and contact the
developer of the GCC.

Christopher Larivière

**Comment by eranif** [comment] 2015-10-31 17:55
Can you explain why did you close this? is this a gcc issue .. or?

**Comment by larivierec** [comment] 2015-10-31 18:20
You're telling me it's the compilers fault, thats the main reason for me closing it. What I find weird is that on Windows 8.1 I was using CodeLite with the exact same compiler and everything was working perfectly.

I've updated my OS to Windows 10 and was expecting both to work the same way (considering it was already working).

I do not have enough knowledge of compilers to know if it is a GCC issue. I've tried updating the compiler to ARM 5.1 and that still did not fix the issue.

The problem could be either Linaro's compiler or CodeLite.

**Comment by mtangoo** [comment] 2015-10-31 18:22
..  Or some change in way windows is working. I suggest you leave it open until you confirm its not CL.

**Comment by eranif** [comment] 2015-10-31 18:25
I have reopened this issue, until we confirm that its not a CodeLite issue.
Did you try running the tests I suggested? (e.g. try compile the files from the command line, replace your make tool etc...)

**Comment by larivierec** [comment] 2015-10-31 18:26
I haven't tried compiling from the command line. Linaro GCC's compiler doesn't have a make. I looked in bin and all extra directories. There seems to not be any.

**Comment by eranif** [comment] 2015-10-31 18:28
Please try and compile it from the command line.
Can you please paste the build output _not_ as image, but as text to this issue?

**Comment by larivierec** [comment] 2015-10-31 18:42
Alright so, from the command line it seems to work except it doesn't have all the configuration that CodeLite IDE handles for my libraries:

make[1]: Entering directory '/cygdrive/d/Chris_Dev/CodeLiteWP/CPPWP/hasframework'
D:/Software/LinaroGCC/bin/arm-linux-gnueabihf-gcc.exe  -c  "D:/Chris_Dev/CodeLiteWP/CPPWP/hasframework/src/Network/Server.cpp" -g -O0 -std=c++11 -Wall  -D__NO_INLINE__  -o ./Debug/Network_Server.cpp.o -Iinclude/ -ID:\libraries\boost_1_57_0 -ID:\libraries\websocketpp
In file included from D:/Chris_Dev/CodeLiteWP/CPPWP/hasframework/src/Network/Server.cpp:1:0:
include/Network/Server.hpp:7:44: fatal error: boost/thread/recursive_mutex.hpp: No such file or directory
compilation terminated.
HAS_Framework.mk:96: recipe for target 'Debug/Network_Server.cpp.o' failed
make[1]: *** [Debug/Network_Server.cpp.o] Error 1
make[1]: Leaving directory '/cygdrive/d/Chris_Dev/CodeLiteWP/CPPWP/hasframework'
Makefile:4: recipe for target 'All' failed
make: *** [All] Error 2

--------------------------------

The one coming from CodeLite outputs this:

mingw32-make[1]: Entering directory 'D:/Chris_Dev/CodeLiteWP/CPPWP/hasframework'
D:/Software/LinaroGCC/bin/arm-linux-gnueabihf-gcc.exe  -c  "D:/Chris_Dev/CodeLiteWP/CPPWP/hasframework/src/Network/Server.cpp" -g -O0 -std=c++11 -Wall  -D__NO_INLINE__  -o ./Debug/Network_Server.cpp.o -Iinclude/ -ID:\libraries\boost_1_57_0 -ID:\libraries\websocketpp
arm-linux-gnueabihf-gcc.exe: error: D:/Chris_Dev/CodeLiteWP/CPPWP/hasframework/src/Network/Server.cpp -g: No such file or directory
arm-linux-gnueabihf-gcc.exe: fatal error: no input files
compilation terminated.
mingw32-make[1]: *** [Debug/Network_Server.cpp.o] Error 1
HAS_Framework.mk:96: recipe for target 'Debug/Network_Server.cpp.o' failed
mingw32-make[1]: Leaving directory 'D:/Chris_Dev/CodeLiteWP/CPPWP/hasframework'






I apologize for the wall of text.

**Comment by eranif** [comment] 2015-10-31 19:02
Notice the difference:
You are compiling from `cygwin` terminal which uses `make` instead of `mingw32-make`
this is a big difference ...

Try this:
* Close CodeLite
* Open CodeLIte from within the `cygwin` termina, i.e. type `"C:\Program Files\CodeLite\codelite.exe"` from the terminal
* Change the make tool from: settings->build settings->compilers->[your compiler name]->Make to use cygwin make tool

The important part is to start CodeLite from within a cygwin terminal

**Comment by eranif** [comment] 2015-10-31 19:03
Also, you did not try to compile as CodeLite does, you should try and run from the command line the exact command as CodeLite does

**Comment by larivierec** [comment] 2015-10-31 19:36
The thing is I dont want to use Cygwin. I recently installed it because it was the only tool that I had to use the "make" tool. Now I have GNU Make and it gives exactly the same errors as the CodeLite error...

I find it redundant to use a software to open another software.

**Comment by eranif** [comment] 2015-10-31 19:39
What happens when you run this from the command line (CMD.EXE):

```
D:/Software/LinaroGCC/bin/arm-linux-gnueabihf-gcc.exe -c "D:/Chris_Dev/CodeLiteWP/CPPWP/hasframework/src/Network/Server.cpp" -g -O0 -std=c++11 -Wall -D__NO_INLINE__ -o ./Debug/Network_Server.cpp.o -Iinclude/ -ID:\libraries\boost_1_57_0 -ID:\libraries\websocketpp
```

**Comment by larivierec** [comment] 2015-10-31 19:48
Nothing... but i dont understand how this exact thing compiles perfectly on Linux CodeLite

**Comment by eranif** [comment] 2015-10-31 20:47
You got give me more than this... "Nothing" ? when you typed the above command you got nothing?

**Comment by larivierec** [comment] 2015-10-31 20:51
My apologies haha... it was a compilation error because it wasn't finding the Boost library <boost/thread/recursive_mutex.hpp> file not found. Even though the include was specifically specified

**Comment by eranif** [comment] 2015-10-31 20:53
So this tells us that the problem is somewhere in the `make` (the above command was executed without `make` and it did not complain about the file name)
So try and use a different `mingw32-make`, download `TDM-GCC` from here: http://tdm-gcc.tdragon.net/download and use its `mingw32-make` and see if it helps

**Comment by larivierec** [comment] 2015-10-31 21:15
Alright so good news for you, I used the provided TDM-GCC make and compiler and it works fine everything compiles! However, it seems the bug is with the ARM compiler on Windows it automatically adds a -g tag for no apparent reason..

If you'd like i'll let you close it, thanks for the help. :+1:

**Closed** 2015-10-31 21:31 UTC

**Comment by larivierec** [comment] 2015-10-31 21:34
Just to add, I solved my issue by enclosing the compiler in quotation marks example:

"D:/Software/LinaroGCC/bin/arm-linux-gnueabihf-g++.exe"

The way it was before it wasnt like this

**Comment by candychiu** [comment] 2016-07-27 14:09
@larivierec Great help, thanks.
