### ISSUE TITLE
Output View - Build doesn't refresh until compilation is finished

### ISSUE THREAD

**Issue by yunkot** [eranif/codelite#3047] opened 2022-07-27 19:10 UTC
CodeLite build b78446b5c7e2e19a1dea0371812bb15d01fc6356. Running on Arch with stock wxWidgets version 3.2, GNOME 42.3 on top of Xorg.

When compiling the project with either GCC or Clang, the text in Output View - Build does not seem to refresh until the compilation is finished. If compilation takes a while, the only thing you see during this time is "Entering directory ...".

**Comment by eranif** [comment] 2022-07-28 03:30
was it a wx update that broke it?
or a recent CodeLite commit?

**Comment by yunkot** [comment] 2022-07-29 00:30
Actually, I could compile older CodeLite 14.0.5 with a couple of patches and it seems to exhibit the same issue. So it could be an issue of wxWidgets 3.2. Is there any workaround I can try to force the repaint/refresh?

**Comment by yunkot** [comment] 2022-07-31 23:38
This issue also happens when using latest wxWidgets compiled from GitHub (https://github.com/wxWidgets/wxWidgets/commit/667c5c843b89ed46e3a64242f94487866cb8c3be) and CodeLite build 4a1a818412812385ffdc06ae8316d3645e787c52. Can reproduce it on GNOME 41.4 and GNOME 42.3, both running under Xorg.

**Comment by yunkot** [comment] 2022-11-16 18:47
The problem is still present as of commit dfde6e967eff1c820c116ec2af46cb1e8ea1a025, tested on Arch / Gnome 43.1 / Wayland / wxWidgets 3.2.1. In fact, now when I compile the project, a notification window appears that CodeLite is not responding, offering to terminate it (but if I wait, the compilation finishes normally).

**Comment by uffejakobsen** [comment] 2022-11-16 21:05
I have seen something similar (I believe)

My problem have been around for some months now - I've also seen it recently on builds from master - but I need to get my arms around the actual scenario and nail the actual things that that creates this situation

**Comment by yunkot** [comment] 2023-04-11 18:07
This issue is still present as of commit c40b9c398217c250584089237fbb1a9efd55ccf2, running on Arch / Gnome 43.4 / Wayland / wxWidgets 3.2.2.

**Comment by uffejakobsen** [comment] 2023-04-21 14:13
I can confirm that - runnning on Arch, wx-3.2.2, LxQT/openbox

**Comment by uffejakobsen** [comment] 2023-06-19 09:46
I still see this issue from time to time on latest CL

**Comment by eranif** [comment] 2023-06-20 19:57
I spoke too soon :)
Indeed, I too see this on Windows

**Comment by yunkot** [comment] 2023-06-24 01:51
This issue still exists as of commit 75f3e0da4b3202a88a594f1ad45430ee5006cac2, tested on Debian 12 / Gnome 43.4 / X11 / wxWidgets 3.2.2.

**Comment by yunkot** [comment] 2023-07-20 23:36
As a note, using a single thread for compilation, or just two of them, kind of alleviates this problem. For me, I can still see output progress if I use "make -j2" on my Ryzen 5950X machine, "make -j3" makes it semi-unresponsive. The default "make -j32" produces this issue and on Debian 12 / Gnome, you would get a message asking if you want to wait for CodeLite or have it closed, until the compilation finishes.

**Comment by eranif** [comment] 2023-07-21 11:59
I see no solution other than replace the current control. Can you try and use the new `Terminal` tab? does it refreshes for you?
if it does, I can make some modifications and use it instead (a variant of it) for the build output

**Comment by yunkot** [comment] 2023-07-21 18:55
I do have "Terminal" tab, but it's empty. Is it supposed to be like that?

**Comment by eranif** [comment] 2023-07-22 06:09
completely empty? you should have a `+` button...

**Comment by yunkot** [comment] 2023-07-22 18:29
Thanks, after pressing on plus symbol, I can see terminal with cursor blinking, although can't type anything in it (how can I use it?). But as soon as I hit "Build", the tab changes and I can't get back to "terminal" tab until the compilation is finished.

**Comment by eranif** [comment] 2023-07-22 19:59
You should be able to type at the bottom of the terminal, cant you?

**Comment by yunkot** [comment] 2023-07-22 20:22
Unfortunately no, I can't type in the terminal - clicking on it and trying to type does not seem to have any effect, like if it was read-only. If you think it's worthwhile, I can report this as a separate (unrelated) issue?

**Comment by eranif** [comment] 2023-07-22 20:26
can you post a screenshot?

**Comment by yunkot** [comment] 2023-07-22 20:35
Yes, sure, here's a screenshot, where cursor is blinking, but typing has no effect (I've blurred user and machine names):
![codelite-terminal-screenshot](https://github.com/eranif/codelite/assets/14065837/d095a95b-0b10-4eb1-aaf3-202e0baf7747)

**Comment by eranif** [comment] 2023-07-22 20:36
This is not a real terminal (but its good enough for basic usage)
Notice the light grey line at the bottom of the terminal -> type there, for example `ls -l`

**Comment by yunkot** [comment] 2023-07-22 20:49
Clicking on light grey line and typing does work, although its cursor is a black square, so a bit difficult to see. But clicking on orange cursor and trying to type text, does not take you to bottom line, although you can move orange cursor around the console with arrow keys and even select text with shift key, however. So at least on my setup, I have to explicitly click on light-grey line to be able to type commands and since there are no other visual clues that this is an edit box, I didn't notice it until you told me to click on it, sorry.

**Comment by eranif** [comment] 2023-07-22 20:52
You can use F6 to toggle focus between the editor <-> terminal without using the mouse
I am currently fixing the cursor colour + hitting any ascii char (a-z/A-Z) will take you to editing line

But the main thing that I wanted to check here:
Can you try and trigger a build using this terminal and see if it refreshes the view?

**Comment by yunkot** [comment] 2023-07-22 21:02
Unfortunately, as I've said earlier, trying to type, e.g. pressing on "A" key while inside terminal does not move focus to bottom edit box. Pressing any keys that start compilation immediately switches to "Build" tab and CodeLite remains unresponsive until it finishes, so I can't switch back. I could only do it if I use "make -j3" to reduce number of threads, but this also allows "Build" tab to refresh, although very subjectively, "Terminal" does look a bit more responsive.

**Comment by eranif** [comment] 2023-07-22 21:05
the number of threads should not affect, I am building with 24 threads and its very responsive (macOS, Windows & Ubuntu)
What I wanted you to try is:

- Open the terminal
- Manually set the focus to the edit area (the last line)
- manually `cd` to the build directory
- run `make -j$(nproc)`

**Comment by yunkot** [comment] 2023-07-22 21:41
I'm pretty sure this issue also happens on Ubuntu as well. I have tested it on latest Arch, Debian 11, Debian 12 and Ubuntu 20.04. I've tried executing "make -j32" in terminal area and it refreshes very well.

**Comment by eranif** [comment] 2023-07-22 21:45
So, making sure here, triggering a build from the terminal (the CodeLite built-in terminal) - works as expected?

**Comment by yunkot** [comment] 2023-07-22 22:21
Yes, that is right. Actually, triggering build from the terminal tab seems to make compilation much faster. So, in my project, pressing F7 and waiting for it to compile takes around 6 seconds, whereas doing the same from terminal tab takes just a second or two. Both execute "make -j32" as far as I can tell.

**Comment by yunkot** [comment] 2023-10-14 21:40
This issue is still present as of CodeLite revision 6246eac495fe34000d0b6494d9d4a2f58e19c495, wxWidgets 3.2.3.

**Comment by eranif** [comment] 2024-12-11 15:46
@yunkot have you been able to use this terminal? my goal is here is to check whether to see if this "view" can show "live" build output. If it can, I will make changes accordingly to the "Build" output.

To test this:

- Click on the `+` button to create new terminal
- `cd` to the workspace folder 
- your build your code using command like `make`

Do you see any "live" output?

**Comment by yunkot** [comment] 2024-12-11 16:42
Since last update, I've switched to Xfce from Gnome, both on Arch and Linux Mint (22, based on Ubuntu 24.04). The issue is slightly less pronounced: Output View gets updated a couple of times during build, unlike it was on Gnome, where it only updated at the end. It seems that using all threads from the CPU makes Output View unresponsive - this happens both on my Ryzen 5950x and newer Ryzen 9800x3D CPUs.

I've tried your instructions using Terminal tab and executing "make -j16": it does seem to refresh perfectly, significantly more responsive.

**Comment by eranif** [comment] 2024-12-11 17:08
Thanks this is the answer I wanted. So I will switch the "Build" view to use the control similar to the "Terminal". This will improve the overall experience

**Comment by yunkot** [comment] 2024-12-12 02:47
That sounds great, looking forward to it!

**Comment by eranif** [comment] 2024-12-24 22:29
Could you please try the latest master?

**Comment by yunkot** [comment] 2024-12-26 19:41
Thanks, the issue is gone now, output is totally responsive. However, when copying text from build output now, some weird UTF-8 sequences sometimes appear, e.g. "�[0m".

Also, unfortunately, CodeLite is unusable now due to regression #3552.

**Comment by eranif** [comment] 2024-12-26 21:06
It's not weird :) its the ANSI escape code which embeds the colours in the text
https://en.wikipedia.org/wiki/ANSI_escape_code#Colors

I will have them removed during copy.
Similar logic was applied to the "Terminal" view:

https://github.com/eranif/codelite/blob/master/Plugin/wxTerminalCtrl/wxTerminalOutputCtrl.cpp#L28

**Comment by yunkot** [comment] 2024-12-26 22:30
Yes, I thought so, but can you apply the filter please? By the way, the coloring in build output does seem to be somewhat weird:
![Weird-coloring](https://github.com/user-attachments/assets/b203981d-8dd3-409a-bfec-c6b7667d69ae)

With the new approach it is also a bit confusing now to see where you can click with the mouse to point to that warning/error location. Should I open a Feature Request for these details?

Otherwise, the issue in question is fixed, I think.

**Comment by eranif** [comment] 2024-12-26 22:35
Closing this as it seems to be fixed now

**Closed by eranif** 2024-12-26 22:35 UTC
Labels: bug

**Comment by eranif** [comment] 2024-12-26 22:53
> With the new approach it is also a bit confusing now to see where you can click with the mouse to point to that warning/error location. Should I open a Feature Request for these details?

Everything is clickable, if it is a URL - it will loaded into a browser. If it is a file:line:column -> it will be opened in CodeLite

**Comment by eranif** [comment] 2024-12-27 10:12
>Thanks, the issue is gone now, output is totally responsive. However, when copying text from build output now, some weird UTF-8 sequences sometimes appear, e.g. "�[0m".

This is now fixed in commit 8edfa1b958977f36b229b2dc2869315b7b0a257c

**Comment by yunkot** [comment] 2024-12-27 21:56
By the way, copying text from Build panel to clipboard now seems to be misbehaving when trying to copy text from the line that has file path (the one that looks like a clickable link): trying to copy text from there actually copies text from next line.  I suppose this was caused by the change of Build UI control? Should I open a separate issue for it?
