### ISSUE TITLE
[Bug]: Fails to build

### ISSUE THREAD

**Issue by mattreecebentley** [eranif/codelite#3136] opened 2023-01-24 06:47 UTC
### What happened?

Was previously using 16.5, had no issues.
Just upgraded to 17, and failing to build under nuwen mingw gcc (latest).
Win10 x64, non-self-compiled.

Message as follows:
"C:/programming/libraries/mingw/bin/mingw32-make.exe -j2 -e -f  Makefile
"----------Building project:[ plf_colony - Debug ]----------"
mingw32-make[1]: Entering directory 'C:/programming/workspaces/plf_colony_x64'
process_begin: CreateProcess(NULL, makedir Debug, ...) failed.
make (e=2): The system cannot find the file specified.
mingw32-make[1]: *** [plf_colony.mk:90: Debug/.d] Error 2
mingw32-make: *** [Makefile:5: All] Error 2
mingw32-make[1]: Leaving directory 'C:/programming/workspaces/plf_colony_x64'
=== build completed successfully (0 errors, 0 warnings) ==="

### Version

Self compiled

### Operating system

Windows 10

### Steps to reproduce

```text
Rebuild project
```

**Comment by eranif** [comment] 2023-01-24 08:15
Duplicate of https://github.com/eranif/codelite/issues/3134
A workaround can be found here: 
https://stackoverflow.com/questions/75097067/codelite-17-0-0-occurs-process-begin-createprocessnull-makedir-debug-f/75106995#75106995

**Closed by eranif** 2023-01-24 08:15 UTC
Labels: bug
