### ISSUE TITLE
Clang Compiler error

### ISSUE THREAD

**Issue by TheAifam5** [eranif/codelite#683] opened 2015-02-25 11:44 UTC
Version CodeLite: 7.1 (x64) - Weekly Build Feb 22, 2015
Version Clang: LLVM 3.7.0 svn-r230157 (x86)
Configuration Clang:
![Configuration](http://i.imgur.com/LdTQsub.png)

main.cpp
```
#include <iostream>

int main(int argc, char **argv)
{
    std::cout << "Hello World" << std::endl;
    return 0;
}
```

Return:
```
C:\Windows\system32\cmd.exe /C "C:/TDM-GCC-64/bin/mingw32-make.exe -j8 SHELL=cmd.exe -e -f  Makefile"
"----------Building project:[ Test - Debug ]----------"
mingw32-make.exe[1]: Entering directory 'C:/Users/TheAifam5/Documents/CodeLite Workspace/TestClang/Test'
'makedir' is not recognized as an internal or external command, operable program or batch file.
mingw32-make.exe[1]: *** [Debug/.d] Error 1
mingw32-make.exe[1]: *** Waiting for unfinished jobs....
'codelite-cc' is not recognized as an internal or external command, operable program or batch file.
mingw32-make.exe[1]: *** [Debug/main.cpp.o.d] Error 1
Test.mk:84: recipe for target 'Debug/.d' failed
Test.mk:95: recipe for target 'Debug/main.cpp.o.d' failed
mingw32-make.exe[1]: Leaving directory 'C:/Users/TheAifam5/Documents/CodeLite 
Workspace/TestClang/Test'
mingw32-make.exe: *** [All] Error 2
Makefile:4: recipe for target 'All' failed
1 errors, 0 warnings
```

**Comment by eranif** [comment] 2015-02-25 11:52
`codelite-cc` is installed under the same folder where you have installed CodeLite (usually it is under: `C:\Program Files \CodeLite` )

Can you please paste here the content of your environment variables as defined by CodeLite from:

`Settings->Environment variables`

Looks like that CodeLite can not locate any of the executable that is should be able to locate by default (they are installed next to the main binary `codelite.exe`)

**Comment by TheAifam5** [comment] 2015-02-25 11:55
Only this:
```
CodeLiteDir=C:\Program Files\CodeLite
```

**Comment by eranif** [comment] 2015-02-25 11:57
What happens if you create your workspace in a folder without space in its path?

**Comment by TheAifam5** [comment] 2015-02-25 12:01
The same.
```
C:\Windows\system32\cmd.exe /C "C:/TDM-GCC-64/bin/mingw32-make.exe -j8 SHELL=cmd.exe -e -f  Makefile"
"----------Building project:[ TestApp - Debug ]----------"
mingw32-make.exe[1]: Entering directory 'C:/Test/TEstErrrr/TestApp'
'makedir' is not recognized as an internal or external command,
operable program or batch file.
mingw32-make.exe[1]: *** [Debug/.d] Error 1
mingw32-make.exe[1]: *** Waiting for unfinished jobs....
TestApp.mk:84: recipe for target 'Debug/.d' failed
'"C:/Program Files (x86)/LLVM/bin/clang++.exe"-std' is not recognized as an internal or external command,
operable program or batch file.
mingw32-make.exe[1]: *** [Debug/main.cpp.o.d] Error 1
mingw32-make.exe: *** [All] Error 2
TestApp.mk:95: recipe for target 'Debug/main.cpp.o.d' failed
mingw32-make.exe[1]: Leaving directory 'C:/Test/TEstErrrr/TestApp'
Makefile:4: recipe for target 'All' failed
1 errors, 0 warnings
```

**Comment by TheAifam5** [comment] 2015-02-25 12:02
```
C:\Windows\system32\cmd.exe /C "C:/TDM-GCC-64/bin/mingw32-make.exe -j8 SHELL=cmd.exe -e -f  Makefile"
"----------Building project:[ TestApp - Debug ]----------"
mingw32-make.exe[1]: Entering directory 'C:/Test/TEstErrrr/TestApp'
'makedir' is not recognized as an internal or external command,
operable program or batch file.
mingw32-make.exe[1]: *** [Debug/.d] Error 1
mingw32-make.exe[1]: *** Waiting for unfinished jobs....
TestApp.mk:84: recipe for target 'Debug/.d' failed
'"C:/Program Files (x86)/LLVM/bin/clang++.exe"-std' is not recognized as an internal or external command,
operable program or batch file.
mingw32-make.exe[1]: *** [Debug/main.cpp.o.d] Error 1
mingw32-make.exe: *** [All] Error 2
TestApp.mk:95: recipe for target 'Debug/main.cpp.o.d' failed
mingw32-make.exe[1]: Leaving directory 'C:/Test/TEstErrrr/TestApp'
Makefile:4: recipe for target 'All' failed
1 errors, 0 warnings
```

**Comment by eranif** [comment] 2015-02-25 12:03
OK, try remove this option:
`settings->code completion->clang->enable clang code completion`

**Comment by TheAifam5** [comment] 2015-02-25 12:04
Is fresh install .. i only added Clang from path. And maked project "clang++ console"...
Option "enable clang code completion" is disabled

**Comment by eranif** [comment] 2015-02-25 12:04
> only added Clang from path

What does this mean?

**Comment by TheAifam5** [comment] 2015-02-25 12:07
I have installed Clang here: "C:\Program Files (x86)\LLVM" and added to "Compilers" using "Add an existing compiler".
in last log: ``'"C:/Program Files (x86)/LLVM/bin/clang++.exe"-std' is not recognized as an internal or external command, operable program or batch file.``. i added space but always the same.

**Comment by TheAifam5** [comment] 2015-02-25 12:08
You wanna TeamViewer (v.10) ?

**Comment by eranif** [comment] 2015-02-25 12:09
I am at work now, so lets see if I can assist like this. If not, later on I can help you from home using Skype/TeamViewer

**Comment by eranif** [comment] 2015-02-25 12:10
BTW, do you have this option enabled:
Settings->Global Editor Preferences->Terminal->Windows only. command executed with .... ?

**Comment by TheAifam5** [comment] 2015-02-25 12:13
Yes I have enabled.. but with disabled is like the same...

With disabled option:
```
C:\Windows\system32\cmd.exe /C C:/TDM-GCC-64/bin/mingw32-make.exe -j8 SHELL=cmd.exe -e -f  Makefile
"----------Building project:[ TestApp - Debug ]----------"
mingw32-make.exe[1]: Entering directory 'C:/Test/TEstErrrr/TestApp'
'makedir' is not recognized as an internal or external command,
operable program or batch file.
mingw32-make.exe[1]: *** [Debug/.d] Error 1
mingw32-make.exe[1]: *** Waiting for unfinished jobs....
'codelite-cc' is not recognized as an internal or external command,
operable program or batch file.
TestApp.mk:84: recipe for target 'Debug/.d' failed
mingw32-make.exe[1]: *** [Debug/main.cpp.o.d] Error 1
mingw32-make.exe: *** [All] Error 2
TestApp.mk:95: recipe for target 'Debug/main.cpp.o.d' failed
mingw32-make.exe[1]: Leaving directory 'C:/Test/TEstErrrr/TestApp'
Makefile:4: recipe for target 'All' failed
1 errors, 0 warnings
```

Enabled Option:
```
C:\Windows\system32\cmd.exe /C "C:/TDM-GCC-64/bin/mingw32-make.exe -j8 SHELL=cmd.exe -e -f  Makefile"
"----------Building project:[ TestApp - Debug ]----------"
mingw32-make.exe[1]: Entering directory 'C:/Test/TEstErrrr/TestApp'
'makedir' is not recognized as an internal or external command,
operable program or batch file.
mingw32-make.exe[1]: *** [Debug/.d] Error 1
mingw32-make.exe[1]: *** Waiting for unfinished jobs....
'codelite-cc' is not recognized as an internal or external command,
operable program or batch file.
mingw32-make.exe[1]: *** [Debug/main.cpp.o.d] Error 1
TestApp.mk:84: recipe for target 'Debug/.d' failed
TestApp.mk:95: recipe for target 'Debug/main.cpp.o.d' failed
mingw32-make.exe[1]: Leaving directory 'C:/Test/TEstErrrr/TestApp'
mingw32-make.exe: *** [All] Error 2
Makefile:4: recipe for target 'All' failed
1 errors, 0 warnings
```

**Comment by eranif** [comment] 2015-02-25 12:15
Good news (for me): I installed CodeLite on a clean vm did what you described and got the same error.
Should have a solution soon - stay tuned

**Comment by TheAifam5** [comment] 2015-02-25 12:17
Ok i waiting.
So but if program not see a specific file (eg. codelite-cc or makedir), why after add to Env global var PATH "C:\Program Files\CodeLite" working the same and not see. XD

http://prntscr.com/69lz1v

**Comment by eranif** [comment] 2015-02-25 12:35
Ok, the main problem is that you have installed LLVM under `C:\Program Files (x86)\LLVN`
Installing it elsewhere (like C:\LLVM) fixes the invocation line

However, I then had this error:
```
C:/LLVM/bin/clang++.exe -o ./Debug/first.exe @"first.txt" -L.
clang++.exe: error: unable to execute command: program not executable
clang++.exe: error: linker (via gcc) command failed with exit code 1 (use -v to see invocation)
```
If I understand it correctly, it seems like clang is trying to use gcc toolchain for linking.
However, since the GCC installed on my machine is 64 bit version and clang is 32 bit ... it fails

**Comment by eranif** [comment] 2015-02-25 12:39
To fix the above, you should do the following:

* Uninstall LLVM
* Install TDM-GCC 32 bit version (there is no need to uninstall the 64 bit version)
* Let CodeLite scan for compilers `settings -> build settings -> add compiler -> scan machine for compilers`, when the dialog with the installed compilers is shown, make sure that you have selected the GCC 32 bit as the Default compiler for MinGW (it should marked with bold)
* Install LLVM under C:\LLVM 
* Let CodeLite detect it ``settings -> build settings -> add compiler -> add an existing compiler`

Try building your project again, I believe it should work this time

**Comment by eranif** [comment] 2015-02-25 12:41
Also, I have written a wiki document about compiler installation that clearly states such problems:
http://codelite.org/AddNewCompiler/AddNewCompiler

**Comment by eranif** [comment] 2015-02-26 07:23
Any update?

**Comment by TheAifam5** [comment] 2015-02-26 11:24
So, now problems is with includes

```
C:\Windows\system32\cmd.exe /C "C:/TDM-GCC-64/bin/mingw32-make.exe -j8 SHELL=cmd.exe -e -f  Makefile"
"----------Building project:[ TestApp - Debug ]----------"
mingw32-make.exe[1]: Entering directory 'C:/Test/TEstErrrr/TestApp'
codelite-cc C:/LLVM/bin/clang++.exe  -c  "C:/Test/TEstErrrr/TestApp/main.cpp" -g -O0 -Wall  -o ./Debug/main.cpp.o -IC:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++ -IC:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++/x86_64-w64-mingw32 -IC:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++/backward -IC:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/include -IC:/TDM-GCC-64/include -IC:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/include-fixed -IC:/TDM-GCC-64/x86_64-w64-mingw32/include  -I. -I.
In file included from C:/Test/TEstErrrr/TestApp/main.cpp:1:
In file included from C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++\iostream:39:
In file included from C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++\ostream:38:
In file included from C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++\ios:38:
In file included from C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++\iosfwd:39:
C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++\bits/stringfwd.h:74:33: error: use of undeclared identifier 'char16_t'
  template<> struct char_traits<char16_t>;
                                ^
C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++\bits/stringfwd.h:75:33: error: use of undeclared identifier 'char32_t'
  template<> struct char_traits<char32_t>;
                                ^
C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++\bits/stringfwd.h:78:24: error: use of undeclared identifier 'char16_t'
  typedef basic_string<char16_t> u16string;
                       ^
C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++\bits/stringfwd.h:81:24: error: use of undeclared identifier 'char32_t'
  typedef basic_string<char32_t> u32string;
                       ^
In file included from C:/Test/TEstErrrr/TestApp/main.cpp:1:
In file included from C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++\iostream:39:
In file included from C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++\ostream:38:
In file included from C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++\ios:40:
In file included from C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++\bits/char_traits.h:39:
In file included from C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++\bits/stl_algobase.h:61:
C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++\bits/cpp_type_traits.h:184:25: error: use of undeclared identifier 'char16_t'
    struct __is_integer<char16_t>
                        ^
C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++\bits/cpp_type_traits.h:191:25: error: use of undeclared identifier 'char32_t'
    struct __is_integer<char32_t>
                        ^
In file included from C:/Test/TEstErrrr/TestApp/main.cpp:1:
In file included from C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++\iostream:39:
In file included from C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++\ostream:38:
In file included from C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++\ios:40:
In file included from C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++\bits/char_traits.h:39:
In file included from C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++\bits/stl_algobase.h:64:
In file included from C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++\bits/stl_pair.h:59:
In file included from C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++\bits/move.h:57:
C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++\type_traits:206:33: error: use of undeclared identifier 'char16_t'
    struct __is_integral_helper<char16_t>
                                ^
C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++\type_traits:210:33: error: use of undeclared identifier 'char32_t'
    struct __is_integral_helper<char32_t>
                                ^
C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++\type_traits:247:33: error: __int128 is not supported on this target
    struct __is_integral_helper<__int128>
                                ^
C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++\type_traits:251:42: error: __int128 is not supported on this target
    struct __is_integral_helper<unsigned __int128>
                                         ^
C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++\type_traits:279:39: error: use of undeclared identifier '__float128'
    struct __is_floating_point_helper<__float128>
                                      ^
C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++\type_traits:1623:28: error: __int128 is not supported on this target
    struct __make_unsigned<__int128>
                           ^
C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++\type_traits:1624:24: error: __int128 is not supported on this target
    { typedef unsigned __int128 __type; };
                       ^
C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++\type_traits:1711:26: error: use of undeclared identifier 'char16_t'
    struct __make_signed<char16_t> : __make_signed<uint_least16_t>
                         ^
C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++\type_traits:1714:26: error: use of undeclared identifier 'char32_t'
    struct __make_signed<char32_t> : __make_signed<uint_least32_t>
                         ^
C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++\type_traits:1720:35: error: __int128 is not supported on this target
    struct __make_signed<unsigned __int128>
                                  ^
C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++\type_traits:1721:15: error: __int128 is not supported on this target
    { typedef __int128 __type; };
              ^
In file included from C:/Test/TEstErrrr/TestApp/main.cpp:1:
In file included from C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++\iostream:39:
In file included from C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++\ostream:38:
In file included from C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++\ios:40:
C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++\bits/char_traits.h:387:24: error: use of undeclared identifier 'char16_t'
    struct char_traits<char16_t>
                       ^
C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++\bits/char_traits.h:480:24: error: use of undeclared identifier 'char32_t'
    struct char_traits<char32_t>
                       ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
mingw32-make.exe[1]: *** [Debug/main.cpp.o] Error 1
mingw32-make.exe: *** [All] Error 2
TestApp.mk:93: recipe for target 'Debug/main.cpp.o' failed
mingw32-make.exe[1]: Leaving directory 'C:/Test/TEstErrrr/TestApp'
Makefile:4: recipe for target 'All' failed
20 errors, 23 warnings
```

Include Paths:
```C:\TDM-GCC-64\lib\gcc\x86_64-w64-mingw32\4.9.2\include\c++
C:\TDM-GCC-64\lib\gcc\x86_64-w64-mingw32\4.9.2\include\c++\x86_64-w64-mingw32
C:\TDM-GCC-64\lib\gcc\x86_64-w64-mingw32\4.9.2\include\c++\backward
C:\TDM-GCC-64\lib\gcc\x86_64-w64-mingw32\4.9.2\include
C:\TDM-GCC-64\include
C:\TDM-GCC-64\lib\gcc\x86_64-w64-mingw32\4.9.2\include-fixed
C:\TDM-GCC-64\x86_64-w64-mingw32\include```

**Comment by eranif** [comment] 2015-02-26 13:53
> Include Paths (Generated by CodeLite):
Where did you take these paths from?

The problem is that clang is not built to work out of the box on Windows and it rely on other compilers to ptovide it with the SDK.

Also, since the MinGW you have installed is **64** bit it will definitely won't work since clang is **32** bit (did you follow the steps in asked in the previous post?)

**Comment by TheAifam5** [comment] 2015-02-26 14:32
c++: ``C:/LLVM/bin/clang++.exe -std=c++14 -fno-ms-compatibility``
IncPath: ``C:\TDM-GCC-64\lib\gcc\x86_64-w64-mingw32\4.9.2\include\c++;C:\TDM-GCC-64\lib\gcc\x86_64-w64-mingw32\4.9.2\include\c++\x86_64-w64-mingw32\32;C:\TDM-GCC-64\lib\gcc\x86_64-w64-mingw32\4.9.2\include\c++\backward;C:\TDM-GCC-64\lib\gcc\x86_64-w64-mingw32\4.9.2\include;C:\TDM-GCC-64\include;C:\TDM-GCC-64\lib\gcc\x86_64-w64-mingw32\4.9.2\include-fixed;C:\TDM-GCC-64\x86_64-w64-mingw32\include``
LinkPath: ``C:\TDM-GCC-64\x86_64-w64-mingw32\lib32;C:\TDM-GCC-64\lib\gcc\x86_64-w64-mingw32\4.9.2\32``

```
C:\Windows\system32\cmd.exe /C "C:/TDM-GCC-64/bin/mingw32-make.exe -j8 SHELL=cmd.exe -e -f  Makefile"
"----------Building project:[ TestApp - Debug ]----------"
mingw32-make.exe[1]: Entering directory 'C:/Test/TEstErrrr/TestApp'
C:/LLVM/bin/clang++.exe -o ./Debug/TestApp @"TestApp.txt" -LC:/TDM-GCC-64/x86_64-w64-mingw32/lib32 -LC:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/32  -L.  -lstdc++
clang++.exe: warning: argument unused during compilation: '-LC:/TDM-GCC-64/x86_64-w64-mingw32/lib32'
clang++.exe: warning: argument unused during compilation: '-LC:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/32'
clang++.exe: warning: argument unused during compilation: '-L.'
LINK : warning LNK4044: unrecognized option '/Z-reserved-lib-stdc++'; ignored
main.cpp.o : error LNK2019: unresolved external symbol "public: __thiscall std::ios_base::Init::Init(void)" (??0Init@ios_base@std@@QAE@XZ) referenced in function "void __cdecl std::`dynamic initializer for '__ioinit''(void)" (??__E__ioinit@std@@YAXXZ)
main.cpp.o : error LNK2019: unresolved external symbol "public: __thiscall std::ios_base::Init::~Init(void)" (??1Init@ios_base@std@@QAE@XZ) referenced in function "void __cdecl std::`dynamic atexit destructor for '__ioinit''(void)" (??__F__ioinit@std@@YAXXZ)
main.cpp.o : error LNK2019: unresolved external symbol "class std::basic_ostream<char,struct std::char_traits<char> > std::cout" (?cout@std@@3V?$basic_ostream@DU?$char_traits@D@std@@@1@A) referenced in function _main
main.cpp.o : error LNK2019: unresolved external symbol "class std::basic_ostream<char,struct std::char_traits<char> > & __cdecl std::operator<<<struct std::char_traits<char> >(class std::basic_ostream<char,struct std::char_traits<char> > &,char const *)" (??$?6U?$char_traits@D@std@@@std@@YAAAV?$basic_ostream@DU?$char_traits@D@std@@@0@AAV10@PBD@Z) referenced in function _main
main.cpp.o : error LNK2019: unresolved external symbol "class std::basic_ostream<char,struct std::char_traits<char> > & __cdecl std::endl<char,struct std::char_traits<char> >(class std::basic_ostream<char,struct std::char_traits<char> > &)" (??$endl@DU?$char_traits@D@std@@@std@@YAAAV?$basic_ostream@DU?$char_traits@D@std@@@0@AAV10@@Z) referenced in function _main
main.cpp.o : error LNK2019: unresolved external symbol "public: class std::basic_ostream<char,struct std::char_traits<char> > & __thiscall std::basic_ostream<char,struct std::char_traits<char> >::operator<<(class std::basic_ostream<char,struct std::char_traits<char> > & (__cdecl*)(class std::basic_ostream<char,struct std::char_traits<char> > &))" (??6?$basic_ostream@DU?$char_traits@D@std@@@std@@QAEAAV01@P6AAAV01@AAV01@@Z@Z) referenced in function _main
./Debug/TestApp : fatal error LNK1120: 6 unresolved externals
clang++.exe: error: linker command failed with exit code 1120 (use -v to see invocation)
mingw32-make.exe[1]: *** [Debug/TestApp] Error 1120
mingw32-make.exe: *** [All] Error 2
TestApp.mk:78: recipe for target 'Debug/TestApp' failed
mingw32-make.exe[1]: Leaving directory 'C:/Test/TEstErrrr/TestApp'
Makefile:4: recipe for target 'All' failed
1 errors, 0 warnings
```

but why:
```
clang++.exe: warning: argument unused during compilation: '-LC:/TDM-GCC-64/x86_64-w64-mingw32/lib32'
clang++.exe: warning: argument unused during compilation: '-LC:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/32'
clang++.exe: warning: argument unused during compilation: '-L.'
```

**Comment by eranif** [comment] 2015-02-26 14:56
You should address these questions to the clang mailing list, its not really a codelite issue.
* It seems that you are missing std++ library that you can link against with clang (even though you provided one via the `-lstd++`)
* The `-L...` flags are standard link flags that adds search path for libraries, also you should address these question to the `clang` mailing list

I am closing this issue, has this is not really a codelite issue but a more of a general configuration issue with clang

**Closed by eranif** 2015-02-26 14:56 UTC
