### ISSUE TITLE
Highlight matching brace causes redraw flicker with scrolling over ending brace "}"

### ISSUE THREAD

**Issue by uffejakobsen** [eranif/codelite#648] opened 2015-02-09 22:22 UTC
Highlight matching brace causes redraw flicker with scrolling over ending brace "}"

This is a kind of hard to explain but I'll try

With highlight matching brace enabled
Rolling the cursor over and past the ending brace of a block (brace "}") - cursor needs to touch the ending brace.
This causes redraw flicker on the current and surrounding lines - just like switching an old TV onto an untuned channel.
The redraw flicker is short lived - less than a second - but a pixel mess is clearly seen.

I've not been able to get a good screenshot yet

Codelite 6.1 did not have this problem

Seen with Codelite 7.0 on ArchLinux

**Comment by eranif** [comment] 2015-02-11 15:20
Do you still experience this with latest git master?
I did some fixes that should result reduce it if not make it go away...

**Comment by uffejakobsen** [comment] 2015-02-11 17:05
I still see flicker with the 7.1 build I did now - but the flicker period seems to be a little reduced

**Comment by kchalmer** [comment] 2015-02-11 19:47
I see the same issue on Kubuntu 14.04.  git bisect shows a1dca83d introduced the problem.

It's particularly bad if you scroll over or start typing in a line that has opening and closing braces on it, e.g.:

    if (foo) { bar(); }

**Comment by eranif** [comment] 2015-02-12 09:41
> I see the same issue on Kubuntu 14.04. git bisect shows a1dca83 introduced the problem.
> It's particularly bad if you start typing in a line that has opening and closing braces on it, e.g.:
> `if (foo) { bar(); }`

Can you please give it a try with the latest git master?
I have removed the various calls to `wxCustomStatusBar::Refresh` which in my opinion are the root cause of this issue, although they should only refresh the status bar and not the entire frame...

Instead, I have optimized the drawing to draw the required field only using MemoryDC and Bitmap ("double buffering")

This problems seems to manifest on slow machines. I rarely see this on my Linux box, however, if I perform a full rebuild of CodeLite using all 8 cores, thus utliziing the 100% CPU and I perform a scroll, I see a flicker while moving the mouse up and down and brace highlight is enabled.

The only thing I could think of is updating the status bar Line/Column field (thanks kchalmer for the bisect) . For me the problem is now fixed - can you guys confirm this?

Thanks!

**Comment by kchalmer** [comment] 2015-02-12 17:12
20f9afbf is *much* better for me.  I saw the flicker just once in about a minute of scrolling around and banging the keyboard randomly.  I consider the problem resolved.

Thanks for the quick fix!

**Comment by eranif** [comment] 2015-02-12 17:21
> 20f9afb is much better for me. I saw the flicker just once in about a minute of scrolling around and 
> banging the keyboard randomly. I consider the problem resolved.
> Thanks for the quick fix!

Great to hear that!
Awaiting confirmation from uffejakobsen :)

**Comment by uffejakobsen** [comment] 2015-02-14 15:58
Well the last two days I've been unable to build a working codelite from trunk.
The build is succesful - but starting codelite gives me this error in the logfile:

symbol lookup error: bin/codelite: undefined symbol: clSetManager(IManager*)

despite that the mentioned symbol is present in libplugin.so:
lib/codelite/libplugin.so:000000000020d390 T clSetManager(IManager*)

This problem is seen with both FreeBSD and ArchLinux and I haven't figured out why it does not pick up that lib. I use a simple script to build from trunk and that have not changed the last week...

**Comment by uffejakobsen** [comment] 2015-02-14 16:38
Ok found the issue. The codelite binary contains a RPATH for /usr/lib/codelite in the dynamic ELF header section. Use of RPATH is deprecated (according to man ld.so on ArchLinux) - RUNPATH is preferred. The only difference between RPATH and RUNPATH is that RUNPATH can be overloaded through LD_LIBRARY_PATH env var. The that was what I was trying to do in order to keep the trunk build "away" from my standard codelote 7.0 libraries.

Anyway the redraw flicker is much much better now - I'd say that it is close to gone - nice work :-) :+1:

**Comment by eranif** [comment] 2015-02-14 16:40
> Ok found the issue. The codelite binary contains a RPATH for /usr/lib/codelite in the dynamic ELF 
> header section. Use of RPATH is deprecated (according to man ld.so on ArchLinux) - RUNPATH is 
> preferred. The only difference between RPATH and RUNPATH is that RUNPATH can be overloaded 
> through LD_LIBRARY_PATH env var. The that was what I was trying to do in order to keep the trunk 
> build "away" from my standard codelote 7.0 libraries.

Did you had to patch `CMakeLists.txt` for this to work?

> Anyway the redraw flicker is much much better now - I'd say that it is close to gone - nice work :-) :+1:

Thanks

**Closed by eranif** 2015-02-14 16:40 UTC

**Comment by uffejakobsen** [comment] 2015-02-14 16:45
No, I used the "chrpath" command on the codelite binary in order to remove the embedded ELF RPATH

inspect RPATH:
chrpath -l /path/to/bin/codelite

delete RPATH
chrpath -d /path/to/bin/codelite
