### ISSUE TITLE
Wizard "freezes"

### ISSUE THREAD

**Issue by darkmoon32** [eranif/codelite#758] opened 2015-05-11 06:13 UTC
When I scan compilers in wizard it freeze after showing me the result of search, pressing the next button and selecting theme. On the left  side is arrow still pointing to compilers but I see theme configuration screen. Buttons are responding because I can finish the process, but I can't see the whitespace configuration screen. This is not happening when I am not scanning for compilers. I'm using Ubuntu 14.04.

**Comment by eranif** [comment] 2015-05-11 11:43
Which desktop environment do you use? I could not reproduce this on Linux Mint 17 (which is identical to Ubuntu 14.04)

**Comment by darkmoon32** [comment] 2015-05-11 12:40
I use Unity 7

**Comment by eranif** [comment] 2015-05-11 20:09
Thanks, this is now fixed (happens only with Unity...)

**Closed by eranif** 2015-05-11 20:09 UTC
