### ISSUE TITLE
Text editor doesn't handle Unicode correctly

### ISSUE THREAD

**Issue by ghost** [eranif/codelite#1714] opened 2017-08-09 04:26 UTC
CodeLite: 10.0
OS: Debian Testing/Buster

I need to work with Unicode and I've used strings from [this page](https://mortoray.com/2013/11/27/the-string-type-is-broken/) to test my code. However, when I pasted them into CodeLite, I've encountered several bugs. First, the "noel" string makes cursor stuck after the end quote for one extra ghost character (i.e. cursor doesn't move when I press left or right). Second, cat emojis are displayed as a 3 hex numbers each. When messed a bit with concatenation of these strings, CodeLite plainly crashed when I hit build. Fortunately, I've made a text file that always crashes CodeLite when I try to build it. It has cat emoji (as probably corrupted by CodeLite during saving) as a string literal.

[Main.txt](https://github.com/eranif/codelite/files/1210326/Main.txt)

**Comment by pattisahusiwa** [comment] 2017-08-09 05:23
Just out of curiosity, why do you need that emoji in your source code? what's the purpose?

Seems codelite handle unicode well and doesn't have any problems with the cursor.
![unicode](https://user-images.githubusercontent.com/11484016/29106134-1ebcdf80-7d0e-11e7-9985-d7d377df7827.png)

**Comment by Lyberta** [comment] 2017-08-09 05:26
I didn't feel like reading a file at runtime just to test a case. I was under impression that everything is UTF-8.

**Comment by AJenbo** [comment] 2020-10-23 16:21
Closing, cannot reproduce on Ubuntu 20.10, original reporter went away

**Closed by AJenbo** 2020-10-23 16:21 UTC
