### ISSUE TITLE
codelite-make build error when workspace build configuration name differs from project's

### ISSUE THREAD

**Issue by kr0st** [eranif/codelite#1629] opened 2017-05-03 11:47 UTC
I have a workspace where one of the build configurations is named "Release". A project in this workspace has configuration that is called "Release-32bit". So, by building workspace configuration "Release" you are building a project configuration "Release-32bit".

The same workspace has configuration called "Release-64bit" and the above mentioned project also has configuration "Release-64bit".

codelite-make has no issues building "Release-64bit" configuration but does not work with "Release-32bit". IDE build is not affected - from IDE I can build all configurations successfully. So it seems that project build configuration name should match workspace build configuration name or build fails.

I was able to workaround the issue by making workspace configuration names same with project configuration names.

Here is the command line that failed before the workaround:
```
codelite-make -w fplog.workspace -p spipc_test -c Release-32bit -d rebuild -e

----------Cleaning project:[ spipc_test -  ]----------
make[1]: Entering directory '/var/lib/jenkins/workspace/fplog/build_architecture/x86_32/build_target_os/Linux/codelite'
rm -f -r ./Release/
make[1]: Leaving directory '/var/lib/jenkins/workspace/fplog/build_architecture/x86_32/build_target_os/Linux/codelite'
----------Building project:[ spipc_test -  ]----------
/bin/sh: 1: spipc_test.mk: not found
Makefile:4: recipe for target 'All' failed
make: *** [All] Error 127
```

**Comment by kr0st** [comment] 2017-05-03 11:49
Forgot to mention, CodeLite version 10.0.3

**Comment by eranif** [comment] 2017-05-03 13:13
If the configuration does not exist, then an error message should have appear, similar to this:

```
$codelite-make -w LiteEditor.workspace -p CodeLiteIDE -c Linux_debug
[ERROR ] Could not find configuration Linux_debug for project CodeLiteIDE
```

Another question: CodeLite does not allow you to create configurations with hyphen (`-`) - did you manually changed the project files?

**Comment by kr0st** [comment] 2017-05-03 13:24
Yep, I've seen this message if I use "Release" configuration name that really does not exist for the project but if I specify the existing config that is called "Release-32bit" then I get the described error.

Did not know the rule about hyphens.. most likely you're correct - I've added the configurations by hand, not via the IDE.

So, my bad then and nice IDE btw, thanks!

**Comment by eranif** [comment] 2017-05-03 13:43
Can you create a minimal example workspace with one project that reproduces this error?
If you can create and attach it, I will probably will be able to debug it

**Comment by kr0st** [comment] 2017-05-03 13:47
Will do that.

**Comment by kr0st** [comment] 2017-05-09 12:43
[reproducing_issue.zip](https://github.com/eranif/codelite/files/986579/reproducing_issue.zip)

Added zipped workspace. The only thing you might have to change is compiler - I'm on GCC 4.8.

This works fine: "codelite-make -w fplog.workspace -p spipc_test -c Release-64bit -d rebuild -e"

This fails to build: "codelite-make -w fplog.workspace -p spipc_test -c Release-32bit -d rebuild -e"

However if I rename workspace configurations to match project configurations - there are no more errors.

**Comment by eranif** [comment] 2017-05-09 14:19
Thanks, I will try and test this later on today

**Comment by eranif** [comment] 2017-05-10 05:43
Ok, thanks for the reproduction zip. 
A short summary:
the `-c` is the **Workspace** configuration name, not the project configuration name. i.e. in your example, you should have pass here **Release** and not **Release-32bit** (since you don't have this configuration in the workspace).

However, even when you pass the correct workspace configuration name, it still fails - this is because of a bug... which is now fixed.

In general, `codelite-make` should behave the same as the UI: In the UI you select the workspace configuration from the drop-down list (at the top of the workspace tab) and you hit `F7`. You don't need to pass the project configuration name (e.g. `Release-32bit`),  since it is already mapped to the workspace configuration (e.g. `Release`)

I also updated the `codelite-make` usage text to clearly indicate that you need to pass the workspace configuration name and not the project configuration name.

I hope I am clear, if not, please consider reading this: http://codelite.org/LiteEditor/ConfigurationManager

**Closed** 2017-05-10 05:44 UTC

**Comment by kr0st** [comment] 2017-05-10 08:05
Thanks for the fix! Everything is absolutely clear.

**Comment by eranif** [comment] 2017-05-10 11:08
I have uploaded CodeLite 10.0.4 to the website which should contains the fix. Please give it a try

**Comment by kr0st** [comment] 2017-05-11 15:54
Fix confirmed, now I get "[ERROR ] Could not find workspace configuration: Release-32bit" if I supply project configuration name instead of workspace configuration to codelite-make. In case I use existing workspace configuration name like "Release" codelite-make is able to build it when in the version 10.0.3 that failed with another error message.
