### ISSUE TITLE
[Ctrl]+[R] conflicting shortcuts

### ISSUE THREAD

**Issue by jjvbsag** [eranif/codelite#1252] opened 2016-04-23 14:53 UTC
Found while testing #1248.
Installed codelite 9.1.5 on a vanilla xubuntu 16.04LTS VM
Key `Ctrl+R` is assigned to `File / Reload File` and to `Search / Find and Replace / Replace ...`

I'd suggest to add a checker to the codelite build process, which parses all keyboard shortcuts and complains about such conflicts.

Regards Jørgen

**Comment by eranif** [comment] 2016-04-23 15:07
Its a duplicate of https://github.com/eranif/codelite/issues/1249

**Closed by eranif** 2016-04-23 15:07 UTC
