### ISSUE TITLE
[Bug]: Repeated crash of codelite

### ISSUE THREAD

**Issue by KUSHAGRA2606** [eranif/codelite#3425] opened 2024-07-13 07:06 UTC
### What happened?

codelite window sometimes automatically get crashed

### Version

17.10.0

### Operating system

Windows 11

### Steps to reproduce

```text
on running a program sometimes codelite get crashed and get logged out
```

**Comment by eranif** [comment] 2024-07-13 07:46
Thanks for reporting this.
Since I don't have Windows 11, could you please run CodeLite under `lldb` ? and report back the backtrace when it happens?

**Comment by eranif** [comment] 2024-07-13 11:20
A duplicate of https://github.com/eranif/codelite/issues/3406

**Closed by eranif** 2024-07-13 11:20 UTC
Labels: bug
