### ISSUE TITLE
Build failure on CentOS 7: wxWidgets is too old

### ISSUE THREAD

**Issue by fusion809** [eranif/codelite#1478] opened 2016-11-21 23:37 UTC
Hi,

I've installed `wxGTK3-devel` on my CentOS 7 VM and its version is greater than 3.0.0, namely, `3.0.2-15`, yet whenever I try to build CodeLite I get the error (with `cmake .. -DCMAKE_INSTALL_PREFIX=/usr`):

```bash
-- SQLITE3_INCLUDE_DIR: /usr/include
-- SQLITE3_LIBRARY: /usr/lib64/libsqlite3.so
-- BUILD_DIRECTORY is set to /codelite-9.2/build
-- OS name Linux
CMake Error at CMakeLists.txt:119 (message):
  

  I'm afraid your wxWidgets version is too old.

  Building CodeLite requires at least wxWidgets-3.0.0


-- Configuring incomplete, errors occurred!
```

and yes I have tried deleting the `build` directory, recreating it and running:

```bash
cmake .. -DCMAKE_INSTALL_PREFIX=/usr
```

from it again (after installing `wxGTK3-devel`).

Thanks for your time,
Brenton

**Comment by eranif** [comment] 2016-11-23 15:21
The question is whether `wx-config` is properly identified?
Try running this from the command line where you run `cmake`:

`wx-config --version`

**Comment by eranif** [comment] 2016-11-26 07:19
Closing this. Not a bug, at worst bad configuration. If you still having problems building CodeLite, please use the gitter chat, IRC channel or the forum

**Closed by eranif** 2016-11-26 07:19 UTC
