### ISSUE TITLE
Word completion is broken if a word contains letters with diacritics

### ISSUE THREAD

**Issue by Greg-21** [eranif/codelite#2710] opened 2021-04-17 17:05 UTC
CodeLite has word completion that works completely fine with words consisting of Latin alphabet letters only but breaks if a word also contains letters with diacritics.

Sample sentences I used for testing and showcasing purposes:
1. A quick brown fox jumps over the lazy dog.
2. Zażółć gęślą jaźń.
3. Červený střízlíček a špinavá žlůva ďobali šťavnaté ocúny.

That's how it currently functions:
![Correct-vs-broken-completion](https://user-images.githubusercontent.com/34160838/115120090-f2ffb380-9fab-11eb-8bfb-17b616e55d94.png)
As you can see here, the word "quick" is suggested correctly, but "zażółć" and "střízlíček" are not.

It is not only a visual bug, see:
![Correct-vs-broken-completion-insertion](https://user-images.githubusercontent.com/34160838/115120181-57227780-9fac-11eb-9c12-8c7ce0576013.png)
After pressing "Enter", the broken suggested text is inserted.

CodeLite version is 15.0.0.
Used font is Consolas (it supports all those characters shown in the screenshots above).

**Comment by eranif** [comment] 2021-04-26 20:47
![word-completion-good](https://user-images.githubusercontent.com/3677711/116148568-bb9ab080-a6e9-11eb-8d17-62df51cd0e8e.png)
Should be fixed now

**Comment by Greg-21** [comment] 2021-04-29 09:05
Thank you. Looking at your screenshot, it seems to work correctly now. I will test it more thoroughly after the next beta build is released.

**Comment by Greg-21** [comment] 2021-05-02 08:25
After some more testing, I can confirm that this issue is indeed fixed in version 15.0.3... but only partially.

If the **entered** text in the editor doesn't contain any letters with diacritics (like in my screenshots above and in yours), the word completion seems to work correctly in 15.0.3.

However, if the **entered** text in the editor, for which the word completion is triggered, contains at least one letter with diacritic (e.g. 'ż' in the first example below, or 'ř' and 'í' in the second one), the word completion breaks again, and instead of inserting only the remaining part of the word, it inserts the entire word starting at the position right behind the last entered letter with diacritic (e.g. in the second example below, the entered letter 'z' has been replaced by 's').

Before pressing "Enter" (on the top) vs after (on the bottom):
![Broken-word-completion](https://user-images.githubusercontent.com/34160838/116806438-46860b80-ab2d-11eb-994f-a3a32e80e0e6.png)

**Comment by eranif** [comment] 2021-05-02 08:46
I suspect that this behaviour is coming from the editing components. By default, CodeLite will search for the starting word position and will attempt to insert the text from the word starting position. Since the by default "words" chars are `a-zA-Z_`, the editor will report wrong "word start position". I was able to reproduce this locally with utf-8 words

**Comment by Greg-21** [comment] 2021-06-22 17:10
Is this an issue in third-party components you rely on, and I should report it to their authors, or within CodeLite? If within CodeLite, how difficult would it be for you to add support for Latin-based diacritics only (not necessarily all UTF-8 ones)?

**Comment by eranif** [comment] 2021-06-23 06:31
no, its not a third party issue. its the way the completion box worked:
when you select an entry from the completion box, CodeLite would then start going backward on the line to search for the insertion point applying the following logic:

```
while current char is a word char:
     go backward one more char

insert selection 
```

The problem with the above is that a `word char` was only `a-zA-Z_$` so it failed to work when it hit a non Latin char

The above logic can be seen here:
https://github.com/eranif/codelite/blob/master/Plugin/wxCodeCompletionBoxManager.cpp#L135

Changing the logic into this fixes the issue:

```
while True:
    if current char is a word delimiter:
        break
    go backward one more char

insert selection
```
Where we now define a word delimiter as member one of the following:

```
std::unordered_set<wxChar> delimiters = { ':', '@', '.', '!',  ' ', '\t', '.', '\\', '+', '*', '-',
                                          '<', '>', '[', ']',  '(', ')',  '{', '}',  '=', '%', '$',
                                          '#', '^', '&', '\'', '/', '|',  ',', '~',  ';', '`' };
```

**Closed** 2021-06-23 06:37 UTC
Labels: Important
