### ISSUE TITLE
Unable to build from source after dist-upgrade to Xubuntu Wily

### ISSUE THREAD

**Issue by jclaveau** [eranif/codelite#1000] opened 2015-11-02 13:50 UTC
Hi everybody,
I just had to update my Xubuntu to Wily because of some problems that were not related to Codelite.
Even if the package from the official repo are recent, i'd like to use Codelite from sources in debug mode to test and report issues to help when I can.

I followed the doc for compiling debug build on Linux and get the following results.

CMakeOutput.log : 
```
The system is: Linux - 4.2.0-16-generic - x86_64
Determining if the C compiler works passed with the following output:
Change Dir: /home/jean/dev/codelite/build-debug/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTryCompileExec2334122911/fast"
/usr/bin/make -f CMakeFiles/cmTryCompileExec2334122911.dir/build.make CMakeFiles/cmTryCompileExec2334122911.dir/build
make[1]: Entering directory '/home/jean/dev/codelite/build-debug/CMakeFiles/CMakeTmp'
/usr/bin/cmake -E cmake_progress_report /home/jean/dev/codelite/build-debug/CMakeFiles/CMakeTmp/CMakeFiles 1
Building C object CMakeFiles/cmTryCompileExec2334122911.dir/testCCompiler.c.o
/usr/bin/cc    -o CMakeFiles/cmTryCompileExec2334122911.dir/testCCompiler.c.o   -c /home/jean/dev/codelite/build-debug/CMakeFiles/CMakeTmp/testCCompiler.c
Linking C executable cmTryCompileExec2334122911
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTryCompileExec2334122911.dir/link.txt --verbose=1
/usr/bin/cc       CMakeFiles/cmTryCompileExec2334122911.dir/testCCompiler.c.o  -o cmTryCompileExec2334122911  
make[1]: Leaving directory '/home/jean/dev/codelite/build-debug/CMakeFiles/CMakeTmp'


Detecting C compiler ABI info compiled with the following output:
Change Dir: /home/jean/dev/codelite/build-debug/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTryCompileExec113659655/fast"
/usr/bin/make -f CMakeFiles/cmTryCompileExec113659655.dir/build.make CMakeFiles/cmTryCompileExec113659655.dir/build
make[1]: Entering directory '/home/jean/dev/codelite/build-debug/CMakeFiles/CMakeTmp'
/usr/bin/cmake -E cmake_progress_report /home/jean/dev/codelite/build-debug/CMakeFiles/CMakeTmp/CMakeFiles 1
Building C object CMakeFiles/cmTryCompileExec113659655.dir/CMakeCCompilerABI.c.o
/usr/bin/cc    -o CMakeFiles/cmTryCompileExec113659655.dir/CMakeCCompilerABI.c.o   -c /usr/share/cmake-3.2/Modules/CMakeCCompilerABI.c
Linking C executable cmTryCompileExec113659655
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTryCompileExec113659655.dir/link.txt --verbose=1
/usr/bin/cc       CMakeFiles/cmTryCompileExec113659655.dir/CMakeCCompilerABI.c.o  -o cmTryCompileExec113659655   
make[1]: Leaving directory '/home/jean/dev/codelite/build-debug/CMakeFiles/CMakeTmp'


Determining if the CXX compiler works passed with the following output:
Change Dir: /home/jean/dev/codelite/build-debug/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTryCompileExec512085536/fast"
/usr/bin/make -f CMakeFiles/cmTryCompileExec512085536.dir/build.make CMakeFiles/cmTryCompileExec512085536.dir/build
make[1]: Entering directory '/home/jean/dev/codelite/build-debug/CMakeFiles/CMakeTmp'
/usr/bin/cmake -E cmake_progress_report /home/jean/dev/codelite/build-debug/CMakeFiles/CMakeTmp/CMakeFiles 1
Building CXX object CMakeFiles/cmTryCompileExec512085536.dir/testCXXCompiler.cxx.o
/usr/bin/c++     -o CMakeFiles/cmTryCompileExec512085536.dir/testCXXCompiler.cxx.o -c /home/jean/dev/codelite/build-debug/CMakeFiles/CMakeTmp/testCXXCompiler.cxx
Linking CXX executable cmTryCompileExec512085536
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTryCompileExec512085536.dir/link.txt --verbose=1
/usr/bin/c++        CMakeFiles/cmTryCompileExec512085536.dir/testCXXCompiler.cxx.o  -o cmTryCompileExec512085536  
make[1]: Leaving directory '/home/jean/dev/codelite/build-debug/CMakeFiles/CMakeTmp'


Detecting CXX compiler ABI info compiled with the following output:
Change Dir: /home/jean/dev/codelite/build-debug/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTryCompileExec3583601035/fast"
/usr/bin/make -f CMakeFiles/cmTryCompileExec3583601035.dir/build.make CMakeFiles/cmTryCompileExec3583601035.dir/build
make[1]: Entering directory '/home/jean/dev/codelite/build-debug/CMakeFiles/CMakeTmp'
/usr/bin/cmake -E cmake_progress_report /home/jean/dev/codelite/build-debug/CMakeFiles/CMakeTmp/CMakeFiles 1
Building CXX object CMakeFiles/cmTryCompileExec3583601035.dir/CMakeCXXCompilerABI.cpp.o
/usr/bin/c++     -o CMakeFiles/cmTryCompileExec3583601035.dir/CMakeCXXCompilerABI.cpp.o -c /usr/share/cmake-3.2/Modules/CMakeCXXCompilerABI.cpp
Linking CXX executable cmTryCompileExec3583601035
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTryCompileExec3583601035.dir/link.txt --verbose=1
/usr/bin/c++        CMakeFiles/cmTryCompileExec3583601035.dir/CMakeCXXCompilerABI.cpp.o  -o cmTryCompileExec3583601035   
make[1]: Leaving directory '/home/jean/dev/codelite/build-debug/CMakeFiles/CMakeTmp'
```

CMakeError.log : 
```
Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
Compiler: /usr/bin/cc 
Build flags: 
Id flags: 

The output was:
1
CMakeCCompilerId.c:183:10: error: macro names must be identifiers
 # define /home/jean/Programmes/CodeLite/COMPILER_VERSION_MAJOR DEC(__GNUC__)
          ^
CMakeCCompilerId.c:184:10: error: macro names must be identifiers
 # define /home/jean/Programmes/CodeLite/COMPILER_VERSION_MINOR DEC(__GNUC_MINOR__)
          ^
CMakeCCompilerId.c:186:11: error: macro names must be identifiers
 #  define /home/jean/Programmes/CodeLite/COMPILER_VERSION_PATCH DEC(__GNUC_PATCHLEVEL__)
           ^


Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
Compiler: /usr/bin/cc 
Build flags: 
Id flags: -c

The output was:
1
CMakeCCompilerId.c:183:10: error: macro names must be identifiers
 # define /home/jean/Programmes/CodeLite/COMPILER_VERSION_MAJOR DEC(__GNUC__)
          ^
CMakeCCompilerId.c:184:10: error: macro names must be identifiers
 # define /home/jean/Programmes/CodeLite/COMPILER_VERSION_MINOR DEC(__GNUC_MINOR__)
          ^
CMakeCCompilerId.c:186:11: error: macro names must be identifiers
 #  define /home/jean/Programmes/CodeLite/COMPILER_VERSION_PATCH DEC(__GNUC_PATCHLEVEL__)
           ^


Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
Compiler: /usr/bin/cc 
Build flags: 
Id flags: -Aa

The output was:
1
<command-line>:0:1: error: missing '(' after predicate
CMakeCCompilerId.c:183:10: error: macro names must be identifiers
 # define /home/jean/Programmes/CodeLite/COMPILER_VERSION_MAJOR DEC(__GNUC__)
          ^
CMakeCCompilerId.c:184:10: error: macro names must be identifiers
 # define /home/jean/Programmes/CodeLite/COMPILER_VERSION_MINOR DEC(__GNUC_MINOR__)
          ^
CMakeCCompilerId.c:186:11: error: macro names must be identifiers
 #  define /home/jean/Programmes/CodeLite/COMPILER_VERSION_PATCH DEC(__GNUC_PATCHLEVEL__)
           ^


Checking whether the C compiler is IAR using "" did not match "IAR .+ Compiler":
cc: fatal error: no input files
compilation terminated.
Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
Compiler: /usr/bin/c++ 
Build flags: 
Id flags: 

The output was:
1
CMakeCXXCompilerId.cpp:185:10: error: macro names must be identifiers
 # define /home/jean/Programmes/CodeLite/COMPILER_VERSION_MAJOR DEC(__GNUC__)
          ^
CMakeCXXCompilerId.cpp:186:10: error: macro names must be identifiers
 # define /home/jean/Programmes/CodeLite/COMPILER_VERSION_MINOR DEC(__GNUC_MINOR__)
          ^
CMakeCXXCompilerId.cpp:188:11: error: macro names must be identifiers
 #  define /home/jean/Programmes/CodeLite/COMPILER_VERSION_PATCH DEC(__GNUC_PATCHLEVEL__)
           ^


Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
Compiler: /usr/bin/c++ 
Build flags: 
Id flags: -c

The output was:
1
CMakeCXXCompilerId.cpp:185:10: error: macro names must be identifiers
 # define /home/jean/Programmes/CodeLite/COMPILER_VERSION_MAJOR DEC(__GNUC__)
          ^
CMakeCXXCompilerId.cpp:186:10: error: macro names must be identifiers
 # define /home/jean/Programmes/CodeLite/COMPILER_VERSION_MINOR DEC(__GNUC_MINOR__)
          ^
CMakeCXXCompilerId.cpp:188:11: error: macro names must be identifiers
 #  define /home/jean/Programmes/CodeLite/COMPILER_VERSION_PATCH DEC(__GNUC_PATCHLEVEL__)
           ^


Checking whether the CXX compiler is IAR using "" did not match "IAR .+ Compiler":
c++: fatal error: no input files
compilation terminated.
```

It worked perfectly before my Xubuntu upgrade so I wonder if this issue comes from the use of do-release-upgrade.

As I'm really bad at understanding all compiler's configuration mess, I really need some help here.

Thanks in advance!

**Comment by jclaveau** [comment] 2015-11-02 13:55
I saved the result of stderr + stdout but it's too long to be shared directly here : 
http://doc.coloc.c277.fr/data/public/a0a6e5

**Comment by eranif** [comment] 2015-11-02 13:55
Can you please run `cmake` without any of these verbose messages, just so I can see the output?
Atm, this looks like a mess to me 

Do this:

```
cd codelite-src
rm -fr build-debug
mkdir build-debug
cmake -DCMAKE_BUILD_TYPE=Debug .. -DPREFIX=/home/jean/root
make -j4

```

**Comment by eranif** [comment] 2015-11-02 14:00
BTW, this looks like a regression in `CMake` which is probably version 3.x

**Comment by eranif** [comment] 2015-11-03 04:27
I installed 15.10/64 on a VB (clean install), did everything according to http://codelite.org/Developers/Linux and it compiles fine...
So it must be an issue with your environment

**Comment by eranif** [comment] 2015-11-03 05:24
I have closed this bug, but feel free to continue posting here or on the #irc channel / forum for more asistance

**Closed** 2015-11-03 05:23 UTC
