### ISSUE TITLE
PHPDoc - class isn't recognized when defined w/o the leading slash

### ISSUE THREAD

**Issue by sgchris** [eranif/codelite#1779] opened 2017-10-09 13:16 UTC
e.g. Class A has namespace, class B hasn't.
--- A.php ---
```php
<?php
namespace NS_A;
class A {
    /**
     * @return B <------- without leading slash "\", it doesn't give completions
     */
    public function getB() {
        return new B();
    }
}
```
--- B.php ---
```php
<?php
// no namespace
class B {
}
```

**Comment by AJenbo** [comment] 2017-10-09 13:22
You need to declare usage of B for it to be valid:
`
<?php
namespace NS_A;
use B;
class A {
    /**
     * @return B <------- without leading slash "\", it doesn't give completions
     */
    public function getB() {
        return new B();
    }
}
`

**Comment by eranif** [comment] 2017-10-09 13:30
@sgchris Greg, I tried running your example code, and this is the error I get:

```
PHP Fatal error:  Uncaught Error: Class 'NS_A\B' not found in C:\Users\PC\Documents\CodeLite\PHP\Php2\Php2\src\G.php:10
Stack trace:
#0 C:\Users\PC\Documents\CodeLite\PHP\Php2\Php2\src\G.php(15): NS_A\A->getB()
#1 {main}
  thrown in C:\Users\PC\Documents\CodeLite\PHP\Php2\Php2\src\G.php on line 10

Fatal error: Uncaught Error: Class 'NS_A\B' not found in C:\Users\PC\Documents\CodeLite\PHP\Php2\Php2\src\G.php:10
Stack trace:
#0 C:\Users\PC\Documents\CodeLite\PHP\Php2\Php2\src\G.php(15): NS_A\A->getB()
#1 {main}
  thrown in C:\Users\PC\Documents\CodeLite\PHP\Php2\Php2\src\G.php on line 10
```

If I add `use B;` as suggested, the code executes perfectly

**Comment by sgchris** [comment] 2017-10-09 13:38
Yes, sure, the original code is defined correctly and it works - The issue is only in PHPDoc and the completions (+"go to definition" on methods). I expected the IDE to be less strict and recognize it without the slash. 

You are right too, so it's up to you whether to fix it or not.

**Comment by AJenbo** [comment] 2017-10-09 13:45
Changing this would mean that the auto-complete would be incorrect in cases where you actually want NS_A\B. Trying to guess what the developer meant can be really tricky and the current behavior serves as a good indication to the developer that something isn't right :)

**Comment by eranif** [comment] 2017-10-09 13:46
@AJenbo actually, I have re-written the namespace resolving for CodeLite 11: it now uses the lookup table to search for class in the current namespace, if it fails, I will try the global namespace

**Comment by pattisahusiwa** [comment] 2017-10-09 14:40
This is wrong syntax. If you define a namespace, you need to add slash to access global classes.
````php
    /**
     * @return B <------- without leading slash "\", it doesn't give completions
     */
    public function getB() {
        return new B();
    }
````
This code MUST be interpreted as `new \NS_A\B()`

I agree with @AJenbo. This issue is not only about convention, but PHP interpreter. Your code maybe recognized by editor, but not by PHP interpreter.

@eranif, please revert the code.

**Comment by pattisahusiwa** [comment] 2017-10-09 14:43
> if it fails, I will try the global namespace

You should not do this. We as developer need to know that the code is wrong. When autocompletion is not working, we know there are errors in the code

**Comment by eranif** [comment] 2017-10-09 15:05
@pattisahusiwa code reverted (it was on my local branch, i just "reset" the files)

**Comment by pattisahusiwa** [comment] 2017-10-10 20:44
Then, this is not a bug anymore. You can close this.

**Closed** 2017-10-25 12:10 UTC
