### ISSUE TITLE
Output Pane not visible even though it is checked in view tab

### ISSUE THREAD

**Issue by greatworldboss** [eranif/codelite#2655] opened 2021-02-08 06:50 UTC
The output pane is not visible in my codelite interface even though it is checked in the view tab. How to fix? I was adjusting the output according to my display and then it suddenly disappeared.

**Comment by dghart** [comment] 2021-02-08 10:13
(This is a question, not a bug-report, and should have been asked in the forum, https://codelite.org/forum/)

You can solve that sort of problem by closing all CodeLite instances, then deleting your CodeLite settings. For example, on Linux that usually means ~/.codelite/. Or you can rename that dir, start CodeLite again, and compare the old with the new.

You can later compare the 2 dirs and either copy the valuable bits from the old dir to the new, or resurrect the old by changing the file that sets the layout; IIRC that's config/*.layout.

**Closed by dghart** 2021-02-08 10:13 UTC
