### ISSUE TITLE
Source code formatting fails

### ISSUE THREAD

**Issue by hsiemannwork** [eranif/codelite#1050] opened 2015-12-02 08:43 UTC
Set indention to 4 and tabsize to 8. if you load a file with these settings, sometimes the tabs are not shown correctly (4 instead of 8 spaces). After pressing Alt+F2 (show whitespace) everything works fine.

**Comment by eranif** [comment] 2015-12-02 08:44
which version of CodeLite? which OS?

**Comment by hsiemannwork** [comment] 2015-12-02 08:45
Codelite 9.0 and Ubuntu 14.04LTS

**Comment by eranif** [comment] 2015-12-02 08:48
This is already fixed. Duplicate of https://github.com/eranif/codelite/issues/1013
You can grab a weekly build with the fix from our download page http://downloads.codelite.org/ (note: weekly builds are not published via the repository)

**Closed by eranif** 2015-12-02 08:48 UTC

**Comment by hsiemannwork** [comment] 2015-12-02 08:53
Ok. Thanks.
