### ISSUE TITLE
Debugger doesn't work on Mac with codelite 

### ISSUE THREAD

**Issue by auredetur** [eranif/codelite#2309] opened 2019-07-30 13:35 UTC
I am trying to use codelite to code but the debugger (LLDB) doesn't work.

When I try to use the debugger then I have this message on the terminal "/tmp/codelite-lldb-helper.sh ; exit;" and the codelite debugging interface do not print anything as variable or other. 

What could I do?

Thank you.

**Comment by KanishkTanwar** [comment] 2019-08-01 18:03
I got on same page, been trying whole day to make it work but failed.
1) Breakpoint disappeared after clicking debug
2) Controls for step in also come up for a second then disappeared

**Comment by killjoy** [comment] 2019-08-13 14:05
My current work around is to use the older command line tools (Command_Line_Tools_macOS_10.13_for_Xcode_10.1.dmg). It installs into /Library/Developer/CommandLineTools/usr/bin and you use xcode-select -s to change from the command line tools in Xcode to codelite.

**Comment by eranif** [comment] 2019-08-17 06:45
Duplicate of https://github.com/eranif/codelite/issues/2295

**Closed by eranif** 2019-08-17 06:45 UTC
