### ISSUE TITLE
CodeLite does not compile

### ISSUE THREAD

**Issue by vikingdawn** [eranif/codelite#3168] opened 2023-03-04 17:19 UTC
Hi 

I just downloades CodeLite and the MSYS compiler and installed all the files according to your instructions. The compiler seems to not working. I cannot compile anything. Not even a "HelloWorld" code. I´m pretty sure that this happens because of the complier. I have a Windows 64. Could you please advise how to make it work?
 Thank you

Best regards,
![image](https://user-images.githubusercontent.com/126977393/222919752-7b0e804d-70ad-4798-aa8a-87a4149431cc.png)
![image](https://user-images.githubusercontent.com/126977393/222919771-cc7df99e-1f04-4785-8071-e9b22b6fcb21.png)
![image](https://user-images.githubusercontent.com/126977393/222919822-a3dedb88-6081-4022-804e-b64e02d5989a.png)

**Comment by eranif** [comment] 2023-03-04 17:24
which version of codelite?

**Comment by vikingdawn** [comment] 2023-03-04 17:33
It´s 17.0.0

**Comment by eranif** [comment] 2023-03-04 17:41
duplicate of https://github.com/eranif/codelite/issues/3134 
use 17.1

**Closed** 2023-03-04 17:52 UTC

**Comment by vikingdawn** [comment] 2023-03-05 14:13
Hi

I did as instructed and upgraded to version 17.1 but nothing changed. The projects don´t compile. Could you please help me solve this? I am a student and I urgently need this solved as the semester just started and I really need this fixed.

Thank you very much 
Best regards,
