### ISSUE TITLE
codelite autocomplete not working

### ISSUE THREAD

**Issue by gudhi987** [eranif/codelite#3214] opened 2023-06-24 06:59 UTC
I am using the latest version of codelite but autocompletion of code is not happening in codelite.
Any suggestions?
@eranif

**Comment by abiiranathan** [comment] 2023-07-11 08:02
Same for me. I installed clang-tools but clangd is no where to be seen.

**Comment by yunkot** [comment] 2023-07-12 16:56
I am also getting this issue with C++ projects, commit 207178f192f54b8c5290079a97547e33328cca5d, running under Debian / Gnome 43.4 / Wayland (or Xorg) / wxWidgets 3.2.2, same on  Arch / Gnome 44.2.

Steps to reproduce:

1. Create a new C++ project in CodeLite.
2. Type "printf("
3. Expected: parameter list to be shown. Actual: nothing happens.
4. Similarly, type "prin". Expected: auto-completion popup with "printf" as suggestion. Actual: nothing happens. Also, pressing Ctrl+Space doesn't show it.

I don't know if it's related, but I've also got CodeLite hangs after opening it for 2nd time (not sure if it tries to open previous workspace, or if it tries to start code scanning for auto-completion). If I remove CodeLite configuration files, it runs normally, but after closing it and re-opening, it hangs again. I've made a fresh CodeLite build on Xfce, where it doesn't hang, but auto-complete is still not working.

Seems to be some kind of regression so I have to keep using a rather old build from 2eb94e53b95f92623d6341465f83bac3bcc19bc3 until this is fixed.

**Comment by eranif** [comment] 2023-07-13 05:01
@yunkot CodeLite uses `clangd` for C++ completion, make sure [it is installed and configured](https://docs.codelite.org/plugins/lsp/#install-language-servers)

**Comment by yunkot** [comment] 2023-07-13 18:45
> @yunkot CodeLite uses `clangd` for C++ completion, make sure [it is installed and configured](https://docs.codelite.org/plugins/lsp/#install-language-servers)

```
Debian clangd version 14.0.6
Features: linux+grpc
Platform: x86_64-pc-linux-gnu
```
Both clangd and ctagsd language servers are using default configuration, it's a clean installation of CodeLite. I just tried latest build 30b009829e0ac200de7e5480e75d7220b1238ff0 and auto-complete doesn't work there either. For a very simple C++ project, it does seem to work, so the steps I mentioned above to reproduce aren't correct. However, when I open a workspace with my actual project, auto-complete doesn't work. I checked all paths, including "compile_commands.json" and it seems correct, so must be something in CodeLite itself.  The project compiles successfully.

I also tried creating new C++ workspace, then new C++ project using CodeLite MakeFile Generator (previous workspace uses Default), copied all paths and parameters one by one from my previous project. Again, this new project compiles just fine, but auto-complete doesn't work for anything that is declared outside of "main.cpp".

Previous version of CodeLite from build 2eb94e53b95f92623d6341465f83bac3bcc19bc3 from last year, which also uses clangd, works perfectly, however.

**Comment by yunkot** [comment] 2023-07-13 23:57
@eranif : Last working commit for me is 07cec5be35999877bbcaef7dd850e2d7d82f3d48 (Feb 3, 2023). After that commit, compilation was broken on Linux, which was later fixed in commit 3e8fcaa442228eb4993c0ac203015bd1367e7da0 (Feb 8, 2023), at which point auto-complete stopped working. So regression occurred somewhere in between these commits.

**Comment by yunkot** [comment] 2023-07-15 21:54
After more re-compilations and testing, it looks like the regression is introduced in 5bfc572dcb670773efab56c2a227a38da1173f4a.

**Comment by yunkot** [comment] 2023-07-20 23:26
Since this problem is critical to me, I'm offering an incentive worth of $50 USD to help fix this issue in CodeLite.

**Comment by eranif** [comment] 2023-07-21 13:04
First, I am 100% sure its a configuration issue, so follow these steps to help me debug this:

1. Disable `ctagsd`
2. Make sure only `clangd` is enabled
3. Ensure that you have `compile_commands.json` file at the root folder of your workspace (NOTE: in order for `clangd` to work, it requires to have `compile_commands.json` at the current file folder or in one of its parents folders)
4. If no completion appears: enable CodeLite log from `Settings -> Preferences -> Misc -> Log -> Debug`
5. Try to complete something and upload the logs `~/.codelite/logs/lsp.log` and `~/.codelite/log/codelite.log` here

**Comment by yunkot** [comment] 2023-07-21 19:05
Actually, disabling "ctagsd", makes code completion working again. Unfortunately, I can only test CodeLite when running it for the first time due to issue #3229 that I started to experience every time, so "lsp.log" is quite short. Basically, I start CodeLite for the first time, open workspace/project, set log to Debug and then try auto-completion with both language servers enabled. Here are two log files zipped: [logs-2023-07-21.zip](https://drive.google.com/file/d/1rjA4UlrzkKsZYTSPM00uGufLc79kWGp_/view?usp=sharing)

**Comment by eranif** [comment] 2023-07-22 04:51
`ctagsd` is deprecated and shouldn't be enabled. So I am not really interested in debugging why this one does not work...
You should only have `clangd` enabled (default install should have that set, if not this is a bug)

**Comment by yunkot** [comment] 2023-07-22 20:20
@eranif : At least for me the code completion is working now. I'm not OP, so don't know if this issue should be closed or not. In either case, I've wired you 75$ worth of donation, thanks a lot for all your help on this and other issues.

**Closed** 2023-07-22 20:27 UTC
