### ISSUE TITLE
[Bug]: In CodeLite, clipboard suddenly loses its contents

### ISSUE THREAD

**Issue by yunkot** [eranif/codelite#3272] opened 2023-10-15 01:25 UTC
This appears to be a regression as my previous CodeLite build from revision 68d2333346c8120ff7c8dc2b8fdac420e358c6fb does not exhibit this. 

In newest CodeLite revision 6246eac495fe34000d0b6494d9d4a2f58e19c495, every time I use Copy and Paste (Ctrl+C, Ctr+V shortcuts) by either selecting a portion of text with mouse, or double-clicking on some word, there is about 5-10% random chance that clipboard contents will become empty. That is, you select a particular word or a piece of text, copy it to clipboard, then try to paste it, only to realize that clipboard has become empty! 

Unfortunately, with this regression, CodeLite has become unusable, so I have to roll back to my known working build 68d2333346c8120ff7c8dc2b8fdac420e358c6fb until this is fixed. Please let me know if there is anything I can do to help debug this.

### Version

Self-compiled, revision 6246eac495fe34000d0b6494d9d4a2f58e19c495.

### Operating system

Arch Linux / Xorg / wxWidgets 3.2.3

**Comment by yunkot** [comment] 2023-10-15 02:03
Actually, when using latest CodeLite revision 6246eac495fe34000d0b6494d9d4a2f58e19c495 with wxWidgets 3.2.2.1 instead of wxWidgets 3.2.3, the problem no longer seems to occur.

**Comment by eranif** [comment] 2023-10-15 04:47
So, a regression in wx?

**Comment by yunkot** [comment] 2023-10-15 05:13
I don't have enough knowledge of how CodeLite internally uses clipboard functionality of wxWidgets, so can't really tell. But since wxWidgets 3.2.3 is becoming mainstream and unless wxWidgets developers would be wiling to address this on their side, shouldn't CodeLite at minimum have some sort of workaround when using latest wxWidgets 3.2.3? Because otherwise clipboard is unusable.

In either case, during next days I'll try to test this on Debian and/or Wayland to see if it is any different there.

**Comment by uffejakobsen** [comment] 2023-10-18 14:18
I have this problem - also on ArchLinux
@yunkot I guess that you have manually built wx-3.2.3.1 (since it is not available as pkg on ArchLinux) ?

**Comment by eranif** [comment] 2023-10-18 16:03
IIRC, the problem appeared between 3.2.2.1 -> 3.2.3
I will dig into wxWidgets commit in between these releases see if something looks suspicious

**Comment by eranif** [comment] 2023-10-18 16:10
I see this bug presented in wx3.3.0:
https://github.com/wxWidgets/wxWidgets/issues/23650

Does this seem like something you are facing?

**Comment by eranif** [comment] 2023-10-18 16:12
Also: are you using Wayland?

**Comment by yunkot** [comment] 2023-10-18 18:18
My bug report is specifically for CodeLite with wxWidgets 3.2.3 under Xorg, running inside GNOME. I haven't tried using it under Wayland yet.

I'm using wxWidgets downloaded from [Releases](https://github.com/wxWidgets/wxWidgets/releases) page and built according to [CodeLite wiki](https://docs.codelite.org/build/build_wx_widgets/#linux). This is how I downgraded to 3.2.2.1 for the time being, where this issue does not occur.

@eranif : I'm not sure, but that bug report might be unrelated. I have seen a similar issue to that bug report, but again, under Xorg (haven't tried under Wayland) where I can copy text from other editors like Geany or Gedit into VMWare virtual machine (my host is Arch, client is Windows 11), but not from CodeLite. The best workaround that works flawlessly for me is to copy text from CodeLite, paste it into browser, e.g. FireFox, then copy it from there and only then I can paste it to VMWare virtual machine; pasting text into CodeLite from VMWare does work as it should, however.

**Comment by uffejakobsen** [comment] 2023-10-18 23:24
I'm  running with Xorg under LXQt (on ArchLinux)
The problem described in the wxWidgets issue does not seem to be the problem we see here...

**Comment by eranif** [comment] 2023-10-19 06:11
Can you please report this bug in the wxWidgets page?
https://github.com/wxWidgets/wxWidgets/issues/new/choose

**Comment by eranif** [comment] 2023-10-22 18:52
@yunkot  @uffejakobsen - can you try the steps that I mentioned in the ticket I opened in wxWidgets?

**Comment by yunkot** [comment] 2023-10-22 19:30
@eranif : Thanks, as I've mentioned in your post, I am able to reproduce the issue 100% of the time on my configuration. 

P.S. I was also going to try posting this issue on wxWidgets site today, but you beat me to it, and your steps in reproducing it are infallible.

**Comment by uffejakobsen** [comment] 2023-10-22 19:30
> @yunkot @uffejakobsen - can you try the steps that I mentioned in the ticket I opened in wxWidgets?

Sure will give it a try...
I had a hard time trying to report the problem to the wx project.
Before reporting I wanted to be able to reproduce the problem outside CL...
So I compiled two editors also based on wx - and they did not show the problem :-/
I did not think of looking into the examples shiped with wx
I'll give stctest a try

**Comment by eranif** [comment] 2023-10-22 19:36
Yes, I am able to reproduce it as well now with wx3.3, consistently. I have a guess that it might be related to the secondary clipboard (seems like that de-selecting text clear the primary clipboard while it should only clear the secondary clipboard)

**Comment by uffejakobsen** [comment] 2023-10-22 20:49
I can confirm that `stctest` exhibits the exact same problem as I've seen with CL

**Comment by eranif** [comment] 2023-10-22 20:56
for now, I reverted back my local build to wx3.2.1 until this is fixed

**Comment by eranif** [comment] 2023-10-23 03:42
Closing this ticket as it was fixed in wxWidgets

**Closed by eranif** 2023-10-23 03:42 UTC
Labels: bug
