### ISSUE TITLE
[Bug]: codelite c++ no ouptut

### ISSUE THREAD

**Issue by Irakliik** [eranif/codelite#3460] opened 2024-08-31 21:30 UTC
### Describe your idea in details

Hey guys. I have a problem. when I build/rebuild a C++ code in codelite. and when the terminal pops up. there is no output. there is a blank space. it does not give any errors either. just no output.

![image](https://github.com/user-attachments/assets/822dfb09-1894-4f6b-8f16-b1457a59537a)
![image](https://github.com/user-attachments/assets/69cde14c-9045-4743-84bc-040d8ec4f7d9)
![image](https://github.com/user-attachments/assets/8319e612-c58a-4aec-aad9-7d7d324c0fc2)
![image](https://github.com/user-attachments/assets/2dd25b5a-114b-44b4-807f-a34f635bc6d8)
![image](https://github.com/user-attachments/assets/a49dee95-9f15-40cf-9d44-f36c5f773980)
![image](https://github.com/user-attachments/assets/047aac9d-137a-4eed-afa8-f1447be02cfc)

**Comment by eranif** [comment] 2024-09-14 07:43
Duplicate of https://github.com/eranif/codelite/issues/3460

**Closed by eranif** 2024-09-14 07:43 UTC
Labels: Feature
