### ISSUE TITLE
HiDPI support

### ISSUE THREAD

**Issue by daniel792** [eranif/codelite#629] opened 2015-01-10 10:21 UTC
I tested Codelite 7 beta today and it appears the environment doesn't scale perfectly with the high resolution (3200x1800) of my screen, especially when you look at the fonts.
![codelite](https://cloud.githubusercontent.com/assets/10468279/5691186/65865954-98ba-11e4-8848-171062f2a015.png)

(To see the issue more clearly, open the pic in a new tab)

For instance, compare the fonts in the tab bar (File, Edit, View, etc) and the buttons for New Workspace, New Project, etc. to the crisp window title saying CodeLite.

I'm not aware of how easy this is to fix - maybe it's just some sort of flag that needs to be set, maybe it's more difficult.

EDIT: The issue is the same for the code itself which is very blurry. That is far more unpleasant than the UI font.

**Comment by nikhedonia** [comment] 2015-05-01 19:34
i can confirm this issue, a solution would be nice

**Comment by mulle-nat** [comment] 2015-05-07 21:58
+1 It's unusable to me at the moment. Might be a cool IDE, but I don't see anything :)

**Comment by progmboy** [comment] 2016-04-27 02:32
+1

**Comment by ihsan-akin** [comment] 2016-06-17 12:57
+1. I can scale parts due to KDE fonts scale and widget scale but the tabs and menus are so small for me.

**Comment by chocolatkey** [comment] 2016-07-10 21:52
+1 Still unusable today
![HighDPI screen](https://cloud.githubusercontent.com/assets/13407784/16716314/5c52e7aa-46f9-11e6-8de6-6d1ca3886c3b.png)

**Comment by assp1r1n3** [comment] 2016-07-11 21:14
There is a possible workaround.

1. Set `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\SideBySide\PreferExternalManifest` as `DWORD` to `1`
2. Create a file in the same directory as the executable with the name `%programname%.exe.manifest`
3. Paste the following into it:
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0" xmlns:asmv3="urn:schemas-microsoft-com:asm.v3">
    <description>PROGRAMNAME</description>
    <trustInfo xmlns="urn:schemas-microsoft-com:asm.v2">
        <security>
            <requestedPrivileges>
                <requestedExecutionLevel xmlns:ms_asmv3="urn:schemas-microsoft-com:asm.v3"
                               level="asInvoker"
                               ms_asmv3:uiAccess="false">
                </requestedExecutionLevel>
            </requestedPrivileges>
        </security>
    </trustInfo>
    <asmv3:application>
        <asmv3:windowsSettings xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">
            <ms_windowsSettings:dpiAware xmlns:ms_windowsSettings="http://schemas.microsoft.com/SMI/2005/WindowsSettings">false</ms_windowsSettings:dpiAware>
        </asmv3:windowsSettings>
    </asmv3:application>
</assembly>
```

**Comment by chocolatkey** [comment] 2016-07-11 23:57
Yes I know that trick on Windows (you can also just edit the codelite exe's embedded manifest), but how about on Linux?

**Comment by assp1r1n3** [comment] 2016-07-12 00:02
vncdesk runs apps via VNC. Useful for scaling on HiDPI displays.

**Comment by chocolatkey** [comment] 2016-07-12 18:16
I'll check it out, thanks

**Comment by eranif** [comment] 2016-07-20 17:22
This is now fixed for Windows.
I opened a separate bug for Linux https://github.com/eranif/codelite/issues/1347

**Closed** 2016-07-20 17:22 UTC
