### ISSUE TITLE
[Feature Request]: Hide main toolbar

### ISSUE THREAD

**Issue by iHardRock** [eranif/codelite#3221] opened 2023-07-14 12:30 UTC
### Describe your idea in details

Now you can set main toolbar orientation from menu "View -> Main ToolBar Orientation", but you can't hide it.
When you using hotkeys for Run / Debug / Navigate, this toolbar became useless and just consumes space that not good on laptops.

**Comment by eranif** [comment] 2023-07-14 13:10
duplicate of https://github.com/eranif/codelite/issues/3156

**Closed by eranif** 2023-07-14 13:10 UTC
Labels: Feature
