### ISSUE TITLE
ctrl-H freeze when accidentally doing bad search and replace

### ISSUE THREAD

**Issue by grandinj** [eranif/codelite#1526] opened 2017-01-26 10:21 UTC
1. create a document containing a string like "Noel"
2. hit ctrl-H
3. make your strings in the little in-line panel "Noel" and "noel"
4. DO NOT MAKE THE MATCH case-sensitive
5. hit the "Replace All" button
6. Codelite will freeze

It should probably issue a warning dialog here, since this is a stupid thing to do :-)

thanks

**Comment by eranif** [comment] 2017-01-26 13:46
This is a duplicate of https://github.com/eranif/codelite/issues/1519 which is fixed in git master
and will be released as weekly build this weekend

**Closed by eranif** 2017-01-26 13:46 UTC
